/**
 * Emit slim practice list catalogs so list pages do not compile solution banks.
 * Run: npx tsx scripts/emit-practice-lists.ts
 */
import fs from "node:fs";
import path from "node:path";
import { getPythonProgrammingList } from "../src/data/python-programming";
import { getPapcList } from "../src/data/certification/papc-problems";
import { getPythonProgrammingStats } from "../src/data/python-programming";
import { getAllPracticeProblems } from "../src/data/practice";
import { toPracticeListItem, type PracticeListItem } from "../src/lib/practice-list";

function writeList(file: string, exportName: string, data: unknown) {
  const body = `import type { PracticeListItem } from "@/lib/practice-list";

/** Auto-generated by scripts/emit-practice-lists.ts — do not edit by hand. */
export const ${exportName}: PracticeListItem[] = ${JSON.stringify(data, null, 2)};
`;
  fs.writeFileSync(file, body);
  console.log("wrote", file, Array.isArray(data) ? data.length : "");
}

writeList(
  path.join("src", "data", "python-programming-list.generated.ts"),
  "PYTHON_PROGRAMMING_LIST",
  getPythonProgrammingList()
);
writeList(
  path.join("src", "data", "certification", "papc-list.generated.ts"),
  "PAPC_PRACTICE_LIST",
  getPapcList()
);

const stats = getPythonProgrammingStats();
const statsBody = `/**
 * Hub practice totals for pages that must not import the full problem banks.
 * Auto-updated by scripts/emit-practice-lists.ts
 */
export const PYTHON_HUB_BASICS_COUNT = ${stats.kinds.language};
export const PYTHON_HUB_ALGORITHM_COUNT = ${stats.kinds.algorithms};
export const PYTHON_HUB_PRACTICE_TOTAL =
  PYTHON_HUB_BASICS_COUNT + PYTHON_HUB_ALGORITHM_COUNT;

export const PYTHON_HUB_DIFFICULTIES = {
  easy: ${stats.difficulties.easy},
  medium: ${stats.difficulties.medium},
  hard: ${stats.difficulties.hard},
} as const;
`;
fs.writeFileSync(path.join("src", "data", "python-hub-stats.ts"), statsBody);
console.log("wrote python-hub-stats.ts", stats);

const byTopic: Record<string, PracticeListItem[]> = {};
for (const problem of getAllPracticeProblems()) {
  const item = toPracticeListItem(problem);
  const topicId = item.topicId ?? problem.topicId;
  (byTopic[topicId] ??= []).push(item);
}
for (const list of Object.values(byTopic)) {
  list.sort((a, b) => a.order - b.order);
}
const courseBody = `import type { PracticeListItem } from "@/lib/practice-list";

/** Auto-generated by scripts/emit-practice-lists.ts — do not edit by hand. */
export const COURSE_PRACTICE_BY_TOPIC: Record<string, PracticeListItem[]> = ${JSON.stringify(byTopic, null, 2)};
`;
fs.writeFileSync(
  path.join("src", "data", "course-practice-list.generated.ts"),
  courseBody
);
console.log("wrote course-practice-list.generated.ts", Object.keys(byTopic).length, "topics");
