-- Auto-generated hidden tests seed
insert into public.practice_hidden_tests (problem_id, tests_json) values
  ('m1-t1-p01', '{"tests":[{"expectedStdout":"Hello, World!"},{"setup":"# hidden check","expectedStdout":"Hello, World!"}]}'::jsonb),
  ('m1-t1-p02', '{"tests":[{"expectedStdout":"Alex\nData Science"},{"setup":"# hidden check","expectedStdout":"Alex\nData Science"}]}'::jsonb),
  ('m1-t1-p03', '{"tests":[{"expectedStdout":"1\n2\n3"},{"setup":"# hidden check","expectedStdout":"1\n2\n3"}]}'::jsonb),
  ('m1-t1-p04', '{"tests":[{"expectedStdout":"Python is fun"},{"setup":"# hidden check","expectedStdout":"Python is fun"}]}'::jsonb),
  ('m1-t1-p05', '{"tests":[{"expectedStdout":"====\nWelcome to Python\n===="},{"setup":"# hidden check","expectedStdout":"====\nWelcome to Python\n===="}]}'::jsonb),
  ('m1-t1-p06', '{"tests":[{"expectedStdout":"I am Sam learning Python"},{"setup":"# hidden check","expectedStdout":"I am Sam learning Python"}]}'::jsonb),
  ('m1-t1-p07', '{"tests":[{"expectedStdout":"42"},{"setup":"# hidden check","expectedStdout":"42"}]}'::jsonb),
  ('m1-t2-p01', '{"tests":[{"expectedStdout":"Ready"},{"setup":"# hidden check","expectedStdout":"Ready"}]}'::jsonb),
  ('m1-t2-p02', '{"tests":[{"expectedStdout":"A,B"},{"setup":"# hidden check","expectedStdout":"A,B"}]}'::jsonb),
  ('m1-t2-p03', '{"tests":[{"expectedStdout":"1\n2\n3\n4"},{"setup":"# hidden check","expectedStdout":"1\n2\n3\n4"}]}'::jsonb),
  ('m1-t2-p04', '{"tests":[{"expectedStdout":"Pass"},{"setup":"# hidden check","expectedStdout":"Pass"}]}'::jsonb),
  ('m1-t2-p05', '{"tests":[{"expectedStdout":"Hello"},{"setup":"# hidden check","expectedStdout":"Hello"}]}'::jsonb),
  ('m1-t2-p06', '{"tests":[{"expectedStdout":"middle"},{"setup":"# hidden check","expectedStdout":"middle"}]}'::jsonb),
  ('m1-t2-p07', '{"tests":[{"expectedStdout":"Python"},{"setup":"# hidden check","expectedStdout":"Python"}]}'::jsonb),
  ('m1-t3-p01', '{"tests":[{"expectedStdout":"Ready"},{"setup":"# hidden check","expectedStdout":"Ready"}]}'::jsonb),
  ('m1-t3-p02', '{"tests":[{"expectedStdout":"A,B"},{"setup":"# hidden check","expectedStdout":"A,B"}]}'::jsonb),
  ('m1-t3-p03', '{"tests":[{"expectedStdout":"1\n2\n3\n4"},{"setup":"# hidden check","expectedStdout":"1\n2\n3\n4"}]}'::jsonb),
  ('m1-t3-p04', '{"tests":[{"expectedStdout":"Pass"},{"setup":"# hidden check","expectedStdout":"Pass"}]}'::jsonb),
  ('m1-t3-p05', '{"tests":[{"expectedStdout":"Hello"},{"setup":"# hidden check","expectedStdout":"Hello"}]}'::jsonb),
  ('m1-t3-p06', '{"tests":[{"expectedStdout":"middle"},{"setup":"# hidden check","expectedStdout":"middle"}]}'::jsonb),
  ('m1-t3-p07', '{"tests":[{"expectedStdout":"Python"},{"setup":"# hidden check","expectedStdout":"Python"}]}'::jsonb),
  ('m1-t4-p01', '{"tests":[{"expectedStdout":"Ready"},{"setup":"# hidden check","expectedStdout":"Ready"}]}'::jsonb),
  ('m1-t4-p02', '{"tests":[{"expectedStdout":"A,B"},{"setup":"# hidden check","expectedStdout":"A,B"}]}'::jsonb),
  ('m1-t4-p03', '{"tests":[{"expectedStdout":"1\n2\n3\n4"},{"setup":"# hidden check","expectedStdout":"1\n2\n3\n4"}]}'::jsonb),
  ('m1-t4-p04', '{"tests":[{"expectedStdout":"Pass"},{"setup":"# hidden check","expectedStdout":"Pass"}]}'::jsonb),
  ('m1-t4-p05', '{"tests":[{"expectedStdout":"Hello"},{"setup":"# hidden check","expectedStdout":"Hello"}]}'::jsonb),
  ('m1-t4-p06', '{"tests":[{"expectedStdout":"middle"},{"setup":"# hidden check","expectedStdout":"middle"}]}'::jsonb),
  ('m1-t4-p07', '{"tests":[{"expectedStdout":"Python"},{"setup":"# hidden check","expectedStdout":"Python"}]}'::jsonb),
  ('m2-t1-p01', '{"tests":[{"expectedStdout":"Jordan"},{"setup":"# hidden check","expectedStdout":"Jordan"}]}'::jsonb),
  ('m2-t1-p02', '{"tests":[{"expectedStdout":"15"},{"setup":"# hidden check","expectedStdout":"15"}]}'::jsonb),
  ('m2-t1-p03', '{"tests":[{"expectedStdout":"Hello\nPython"},{"setup":"# hidden check","expectedStdout":"Hello\nPython"}]}'::jsonb),
  ('m2-t1-p04', '{"tests":[{"expectedStdout":"Hello, Mia"},{"setup":"# hidden check","expectedStdout":"Hello, Mia"}]}'::jsonb),
  ('m2-t1-p05', '{"tests":[{"expectedStdout":"Name: Leo, Age: 20"},{"setup":"# hidden check","expectedStdout":"Name: Leo, Age: 20"}]}'::jsonb),
  ('m2-t1-p06', '{"tests":[{"expectedStdout":"1 2 3"},{"setup":"# hidden check","expectedStdout":"1 2 3"}]}'::jsonb),
  ('m2-t1-p07', '{"tests":[{"expectedStdout":"a-b-c"},{"setup":"# hidden check","expectedStdout":"a-b-c"}]}'::jsonb),
  ('m2-t2-p01', '{"tests":[{"expectedStdout":"Hi"},{"setup":"# hidden check","expectedStdout":"Hi"}]}'::jsonb),
  ('m2-t2-p02', '{"tests":[{"expectedStdout":"Line1\nLine2"},{"setup":"# hidden check","expectedStdout":"Line1\nLine2"}]}'::jsonb),
  ('m2-t2-p03', '{"tests":[{"expectedStdout":"5"},{"setup":"# hidden check","expectedStdout":"5"}]}'::jsonb),
  ('m2-t2-p04', '{"tests":[{"expectedStdout":"A\nB"},{"setup":"# hidden check","expectedStdout":"A\nB"}]}'::jsonb),
  ('m2-t2-p05', '{"tests":[{"expectedStdout":"1\n2\n3"},{"setup":"# hidden check","expectedStdout":"1\n2\n3"}]}'::jsonb),
  ('m2-t2-p06', '{"tests":[{"expectedStdout":"Hello"},{"setup":"# hidden check","expectedStdout":"Hello"}]}'::jsonb),
  ('m2-t2-p07', '{"tests":[{"expectedStdout":"Pass"},{"setup":"# hidden check","expectedStdout":"Pass"}]}'::jsonb),
  ('m2-t3-p01', '{"tests":[{"expectedStdout":"21"},{"setup":"# hidden check","expectedStdout":"21"}]}'::jsonb),
  ('m2-t3-p02', '{"tests":[{"expectedStdout":"Pune"},{"setup":"# hidden check","expectedStdout":"Pune"}]}'::jsonb),
  ('m2-t3-p03', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m2-t3-p04', '{"tests":[{"expectedStdout":"15"},{"setup":"# hidden check","expectedStdout":"15"}]}'::jsonb),
  ('m2-t3-p05', '{"tests":[{"expectedStdout":"2\n1"},{"setup":"# hidden check","expectedStdout":"2\n1"}]}'::jsonb),
  ('m2-t3-p06', '{"tests":[{"expectedStdout":"88"},{"setup":"# hidden check","expectedStdout":"88"}]}'::jsonb),
  ('m2-t3-p07', '{"tests":[{"expectedStdout":"6"},{"setup":"# hidden check","expectedStdout":"6"}]}'::jsonb),
  ('m2-t4-p01', '{"tests":[{"expectedStdout":"21"},{"setup":"# hidden check","expectedStdout":"21"}]}'::jsonb),
  ('m2-t4-p02', '{"tests":[{"expectedStdout":"3.14"},{"setup":"# hidden check","expectedStdout":"3.14"}]}'::jsonb),
  ('m2-t4-p03', '{"tests":[{"expectedStdout":"Ana"},{"setup":"# hidden check","expectedStdout":"Ana"}]}'::jsonb),
  ('m2-t4-p04', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m2-t4-p05', '{"tests":[{"expectedStdout":"<class ''int''>"},{"setup":"# hidden check","expectedStdout":"<class ''int''>"}]}'::jsonb),
  ('m2-t4-p06', '{"tests":[{"expectedStdout":"<class ''str''>"},{"setup":"# hidden check","expectedStdout":"<class ''str''>"}]}'::jsonb),
  ('m2-t4-p07', '{"tests":[{"expectedStdout":"<class ''int''>\n<class ''float''>"},{"setup":"# hidden check","expectedStdout":"<class ''int''>\n<class ''float''>"}]}'::jsonb),
  ('m2-t5-p01', '{"tests":[{"expectedStdout":"7"},{"setup":"# hidden check","expectedStdout":"7"}]}'::jsonb),
  ('m2-t5-p02', '{"tests":[{"expectedStdout":"3.5"},{"setup":"# hidden check","expectedStdout":"3.5"}]}'::jsonb),
  ('m2-t5-p03', '{"tests":[{"expectedStdout":"42"},{"setup":"# hidden check","expectedStdout":"42"}]}'::jsonb),
  ('m2-t5-p04', '{"tests":[{"expectedStdout":"9"},{"setup":"# hidden check","expectedStdout":"9"}]}'::jsonb),
  ('m2-t5-p05', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m2-t5-p06', '{"tests":[{"expectedStdout":"Score: 100"},{"setup":"# hidden check","expectedStdout":"Score: 100"}]}'::jsonb),
  ('m2-t5-p07', '{"tests":[{"expectedStdout":"1\n0"},{"setup":"# hidden check","expectedStdout":"1\n0"}]}'::jsonb),
  ('m3-t1-p01', '{"tests":[{"expectedStdout":"13"},{"setup":"# hidden check","expectedStdout":"13"}]}'::jsonb),
  ('m3-t1-p02', '{"tests":[{"expectedStdout":"15"},{"setup":"# hidden check","expectedStdout":"15"}]}'::jsonb),
  ('m3-t1-p03', '{"tests":[{"expectedStdout":"24"},{"setup":"# hidden check","expectedStdout":"24"}]}'::jsonb),
  ('m3-t1-p04', '{"tests":[{"expectedStdout":"5.0"},{"setup":"# hidden check","expectedStdout":"5.0"}]}'::jsonb),
  ('m3-t1-p05', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m3-t1-p06', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m3-t1-p07', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m3-t2-p01', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m3-t2-p02', '{"tests":[{"expectedStdout":"15"},{"setup":"# hidden check","expectedStdout":"15"}]}'::jsonb),
  ('m3-t2-p03', '{"tests":[{"expectedStdout":"7"},{"setup":"# hidden check","expectedStdout":"7"}]}'::jsonb),
  ('m3-t2-p04', '{"tests":[{"expectedStdout":"12"},{"setup":"# hidden check","expectedStdout":"12"}]}'::jsonb),
  ('m3-t2-p05', '{"tests":[{"expectedStdout":"5.0"},{"setup":"# hidden check","expectedStdout":"5.0"}]}'::jsonb),
  ('m3-t2-p06', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m3-t2-p07', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m3-t3-p01', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t3-p02', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t3-p03', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t3-p04', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t3-p05', '{"tests":[{"expectedStdout":"False"},{"setup":"# hidden check","expectedStdout":"False"}]}'::jsonb),
  ('m3-t3-p06', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t3-p07', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t4-p01', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t4-p02', '{"tests":[{"expectedStdout":"False"},{"setup":"# hidden check","expectedStdout":"False"}]}'::jsonb),
  ('m3-t4-p03', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t4-p04', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t4-p05', '{"tests":[{"expectedStdout":"False"},{"setup":"# hidden check","expectedStdout":"False"}]}'::jsonb),
  ('m3-t4-p06', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t4-p07', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t5-p01', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t5-p02', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t5-p03', '{"tests":[{"expectedStdout":"False"},{"setup":"# hidden check","expectedStdout":"False"}]}'::jsonb),
  ('m3-t5-p04', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t5-p05', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t5-p06', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t5-p07', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t6-p01', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t6-p02', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t6-p03', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t6-p04', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t6-p05', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t6-p06', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m3-t6-p07', '{"tests":[{"expectedStdout":"True\nFalse"},{"setup":"# hidden check","expectedStdout":"True\nFalse"}]}'::jsonb),
  ('m3-t7-p01', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m3-t7-p02', '{"tests":[{"expectedStdout":"7"},{"setup":"# hidden check","expectedStdout":"7"}]}'::jsonb),
  ('m3-t7-p03', '{"tests":[{"expectedStdout":"4"},{"setup":"# hidden check","expectedStdout":"4"}]}'::jsonb),
  ('m3-t7-p04', '{"tests":[{"expectedStdout":"6"},{"setup":"# hidden check","expectedStdout":"6"}]}'::jsonb),
  ('m3-t7-p05', '{"tests":[{"expectedStdout":"4"},{"setup":"# hidden check","expectedStdout":"4"}]}'::jsonb),
  ('m3-t7-p06', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m3-t7-p07', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m4-t1-p01', '{"tests":[{"expectedStdout":"Hello"},{"setup":"# hidden check","expectedStdout":"Hello"}]}'::jsonb),
  ('m4-t1-p02', '{"tests":[{"expectedStdout":"Python"},{"setup":"# hidden check","expectedStdout":"Python"}]}'::jsonb),
  ('m4-t1-p03', '{"tests":[{"expectedStdout":"Python"},{"setup":"# hidden check","expectedStdout":"Python"}]}'::jsonb),
  ('m4-t1-p04', '{"tests":[{"expectedStdout":"HaHaHa"},{"setup":"# hidden check","expectedStdout":"HaHaHa"}]}'::jsonb),
  ('m4-t1-p05', '{"tests":[{"expectedStdout":"Line1\nLine2"},{"setup":"# hidden check","expectedStdout":"Line1\nLine2"}]}'::jsonb),
  ('m4-t1-p06', '{"tests":[{"expectedStdout":"0"},{"setup":"# hidden check","expectedStdout":"0"}]}'::jsonb),
  ('m4-t1-p07', '{"tests":[{"expectedStdout":"Data Science"},{"setup":"# hidden check","expectedStdout":"Data Science"}]}'::jsonb),
  ('m4-t2-p01', '{"tests":[{"expectedStdout":"Hello, Ana"},{"setup":"# hidden check","expectedStdout":"Hello, Ana"}]}'::jsonb),
  ('m4-t2-p02', '{"tests":[{"expectedStdout":"2 + 3 = 5"},{"setup":"# hidden check","expectedStdout":"2 + 3 = 5"}]}'::jsonb),
  ('m4-t2-p03', '{"tests":[{"expectedStdout":"Score: 90"},{"setup":"# hidden check","expectedStdout":"Score: 90"}]}'::jsonb),
  ('m4-t2-p04', '{"tests":[{"expectedStdout":"3 + 4 = 7"},{"setup":"# hidden check","expectedStdout":"3 + 4 = 7"}]}'::jsonb),
  ('m4-t2-p05', '{"tests":[{"expectedStdout":"Hello World"},{"setup":"# hidden check","expectedStdout":"Hello World"}]}'::jsonb),
  ('m4-t2-p06', '{"tests":[{"expectedStdout":"Pi is 3.14"},{"setup":"# hidden check","expectedStdout":"Pi is 3.14"}]}'::jsonb),
  ('m4-t2-p07', '{"tests":[{"expectedStdout":"Value: 42"},{"setup":"# hidden check","expectedStdout":"Value: 42"}]}'::jsonb),
  ('m4-t3-p01', '{"tests":[{"expectedStdout":"P"},{"setup":"# hidden check","expectedStdout":"P"}]}'::jsonb),
  ('m4-t3-p02', '{"tests":[{"expectedStdout":"n"},{"setup":"# hidden check","expectedStdout":"n"}]}'::jsonb),
  ('m4-t3-p03', '{"tests":[{"expectedStdout":"n"},{"setup":"# hidden check","expectedStdout":"n"}]}'::jsonb),
  ('m4-t3-p04', '{"tests":[{"expectedStdout":"o"},{"setup":"# hidden check","expectedStdout":"o"}]}'::jsonb),
  ('m4-t3-p05', '{"tests":[{"expectedStdout":"l"},{"setup":"# hidden check","expectedStdout":"l"}]}'::jsonb),
  ('m4-t3-p06', '{"tests":[{"expectedStdout":"P\nt"},{"setup":"# hidden check","expectedStdout":"P\nt"}]}'::jsonb),
  ('m4-t3-p07', '{"tests":[{"expectedStdout":"Hi"},{"setup":"# hidden check","expectedStdout":"Hi"}]}'::jsonb),
  ('m4-t4-p01', '{"tests":[{"expectedStdout":"Py"},{"setup":"# hidden check","expectedStdout":"Py"}]}'::jsonb),
  ('m4-t4-p02', '{"tests":[{"expectedStdout":"thon"},{"setup":"# hidden check","expectedStdout":"thon"}]}'::jsonb),
  ('m4-t4-p03', '{"tests":[{"expectedStdout":"Pyt"},{"setup":"# hidden check","expectedStdout":"Pyt"}]}'::jsonb),
  ('m4-t4-p04', '{"tests":[{"expectedStdout":"Pto"},{"setup":"# hidden check","expectedStdout":"Pto"}]}'::jsonb),
  ('m4-t4-p05', '{"tests":[{"expectedStdout":"nohtyP"},{"setup":"# hidden check","expectedStdout":"nohtyP"}]}'::jsonb),
  ('m4-t4-p06', '{"tests":[{"expectedStdout":"ata"},{"setup":"# hidden check","expectedStdout":"ata"}]}'::jsonb),
  ('m4-t4-p07', '{"tests":[{"expectedStdout":"ell"},{"setup":"# hidden check","expectedStdout":"ell"}]}'::jsonb),
  ('m4-t5-p01', '{"tests":[{"expectedStdout":"HELLO"},{"setup":"# hidden check","expectedStdout":"HELLO"}]}'::jsonb),
  ('m4-t5-p02', '{"tests":[{"expectedStdout":"hello"},{"setup":"# hidden check","expectedStdout":"hello"}]}'::jsonb),
  ('m4-t5-p03', '{"tests":[{"expectedStdout":"hi"},{"setup":"# hidden check","expectedStdout":"hi"}]}'::jsonb),
  ('m4-t5-p04', '{"tests":[{"expectedStdout":"[''a'', ''b'', ''c'']"},{"setup":"# hidden check","expectedStdout":"[''a'', ''b'', ''c'']"}]}'::jsonb),
  ('m4-t5-p05', '{"tests":[{"expectedStdout":"a-b-c"},{"setup":"# hidden check","expectedStdout":"a-b-c"}]}'::jsonb),
  ('m4-t5-p06', '{"tests":[{"expectedStdout":"heLLo"},{"setup":"# hidden check","expectedStdout":"heLLo"}]}'::jsonb),
  ('m4-t5-p07', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m5-t1-p01', '{"tests":[{"expectedStdout":"[1, 2, 3]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3]"}]}'::jsonb),
  ('m5-t1-p02', '{"tests":[{"expectedStdout":"0"},{"setup":"# hidden check","expectedStdout":"0"}]}'::jsonb),
  ('m5-t1-p03', '{"tests":[{"expectedStdout":"[1, ''hi'', True]"},{"setup":"# hidden check","expectedStdout":"[1, ''hi'', True]"}]}'::jsonb),
  ('m5-t1-p04', '{"tests":[{"expectedStdout":"[1, 2]"},{"setup":"# hidden check","expectedStdout":"[1, 2]"}]}'::jsonb),
  ('m5-t1-p05', '{"tests":[{"expectedStdout":"[1, 2, 3]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3]"}]}'::jsonb),
  ('m5-t1-p06', '{"tests":[{"expectedStdout":"[0, 0, 0]"},{"setup":"# hidden check","expectedStdout":"[0, 0, 0]"}]}'::jsonb),
  ('m5-t1-p07', '{"tests":[{"expectedStdout":"[1, 2, 3, 4]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3, 4]"}]}'::jsonb),
  ('m5-t2-p01', '{"tests":[{"expectedStdout":"[3, 1, 2]"},{"setup":"# hidden check","expectedStdout":"[3, 1, 2]"}]}'::jsonb),
  ('m5-t2-p02', '{"tests":[{"expectedStdout":"[99, 2]"},{"setup":"# hidden check","expectedStdout":"[99, 2]"}]}'::jsonb),
  ('m5-t2-p03', '{"tests":[{"expectedStdout":"[1, 1, 2]"},{"setup":"# hidden check","expectedStdout":"[1, 1, 2]"}]}'::jsonb),
  ('m5-t2-p04', '{"tests":[{"expectedStdout":"4"},{"setup":"# hidden check","expectedStdout":"4"}]}'::jsonb),
  ('m5-t2-p05', '{"tests":[{"expectedStdout":"<class ''list''>"},{"setup":"# hidden check","expectedStdout":"<class ''list''>"}]}'::jsonb),
  ('m5-t2-p06', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m5-t2-p07', '{"tests":[{"expectedStdout":"[1, ''two'', 3.0]"},{"setup":"# hidden check","expectedStdout":"[1, ''two'', 3.0]"}]}'::jsonb),
  ('m5-t3-p01', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m5-t3-p02', '{"tests":[{"expectedStdout":"30"},{"setup":"# hidden check","expectedStdout":"30"}]}'::jsonb),
  ('m5-t3-p03', '{"tests":[{"expectedStdout":"middle"},{"setup":"# hidden check","expectedStdout":"middle"}]}'::jsonb),
  ('m5-t3-p04', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m5-t3-p05', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m5-t3-p06', '{"tests":[{"expectedStdout":"5\n15"},{"setup":"# hidden check","expectedStdout":"5\n15"}]}'::jsonb),
  ('m5-t3-p07', '{"tests":[{"expectedStdout":"12"},{"setup":"# hidden check","expectedStdout":"12"}]}'::jsonb),
  ('m5-t4-p01', '{"tests":[{"expectedStdout":"[1, 2]"},{"setup":"# hidden check","expectedStdout":"[1, 2]"}]}'::jsonb),
  ('m5-t4-p02', '{"tests":[{"expectedStdout":"[0, 1]"},{"setup":"# hidden check","expectedStdout":"[0, 1]"}]}'::jsonb),
  ('m5-t4-p03', '{"tests":[{"expectedStdout":"[2, 3]"},{"setup":"# hidden check","expectedStdout":"[2, 3]"}]}'::jsonb),
  ('m5-t4-p04', '{"tests":[{"expectedStdout":"[0, 2, 4]"},{"setup":"# hidden check","expectedStdout":"[0, 2, 4]"}]}'::jsonb),
  ('m5-t4-p05', '{"tests":[{"expectedStdout":"[3, 2, 1]"},{"setup":"# hidden check","expectedStdout":"[3, 2, 1]"}]}'::jsonb),
  ('m5-t4-p06', '{"tests":[{"expectedStdout":"[20, 30, 40]"},{"setup":"# hidden check","expectedStdout":"[20, 30, 40]"}]}'::jsonb),
  ('m5-t4-p07', '{"tests":[{"expectedStdout":"[]"},{"setup":"# hidden check","expectedStdout":"[]"}]}'::jsonb),
  ('m5-t5-p01', '{"tests":[{"expectedStdout":"[1, 2, 3]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3]"}]}'::jsonb),
  ('m5-t5-p02', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m5-t5-p03', '{"tests":[{"expectedStdout":"[1, 2, 3]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3]"}]}'::jsonb),
  ('m5-t5-p04', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m5-t5-p05', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m5-t5-p06', '{"tests":[{"expectedStdout":"[1, 2, 3, 4]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3, 4]"}]}'::jsonb),
  ('m5-t5-p07', '{"tests":[{"expectedStdout":"[1, 3, 2]"},{"setup":"# hidden check","expectedStdout":"[1, 3, 2]"}]}'::jsonb),
  ('m5-t6-p01', '{"tests":[{"expectedStdout":"[10, 2, 3]"},{"setup":"# hidden check","expectedStdout":"[10, 2, 3]"}]}'::jsonb),
  ('m5-t6-p02', '{"tests":[{"expectedStdout":"[1, 2, 3]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3]"}]}'::jsonb),
  ('m5-t6-p03', '{"tests":[{"expectedStdout":"[1, 3]"},{"setup":"# hidden check","expectedStdout":"[1, 3]"}]}'::jsonb),
  ('m5-t6-p04', '{"tests":[{"expectedStdout":"[]"},{"setup":"# hidden check","expectedStdout":"[]"}]}'::jsonb),
  ('m5-t6-p05', '{"tests":[{"expectedStdout":"[0, 10, 20, 0]"},{"setup":"# hidden check","expectedStdout":"[0, 10, 20, 0]"}]}'::jsonb),
  ('m5-t6-p06', '{"tests":[{"expectedStdout":"[0, 1, 2]"},{"setup":"# hidden check","expectedStdout":"[0, 1, 2]"}]}'::jsonb),
  ('m5-t6-p07', '{"tests":[{"expectedStdout":"[[1, 9], [3, 4]]"},{"setup":"# hidden check","expectedStdout":"[[1, 9], [3, 4]]"}]}'::jsonb),
  ('m6-t1-p01', '{"tests":[{"expectedStdout":"(1, 2, 3)"},{"setup":"# hidden check","expectedStdout":"(1, 2, 3)"}]}'::jsonb),
  ('m6-t1-p02', '{"tests":[{"expectedStdout":"b"},{"setup":"# hidden check","expectedStdout":"b"}]}'::jsonb),
  ('m6-t1-p03', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m6-t1-p04', '{"tests":[{"expectedStdout":"4"},{"setup":"# hidden check","expectedStdout":"4"}]}'::jsonb),
  ('m6-t1-p05', '{"tests":[{"expectedStdout":"(1, 2)"},{"setup":"# hidden check","expectedStdout":"(1, 2)"}]}'::jsonb),
  ('m6-t1-p06', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m6-t1-p07', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m6-t2-p01', '{"tests":[{"expectedStdout":"(3, 1, 2)"},{"setup":"# hidden check","expectedStdout":"(3, 1, 2)"}]}'::jsonb),
  ('m6-t2-p02', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m6-t2-p03', '{"tests":[{"expectedStdout":"(1, 1, 2)"},{"setup":"# hidden check","expectedStdout":"(1, 1, 2)"}]}'::jsonb),
  ('m6-t2-p04', '{"tests":[{"expectedStdout":"(1, ''a'', True)"},{"setup":"# hidden check","expectedStdout":"(1, ''a'', True)"}]}'::jsonb),
  ('m6-t2-p05', '{"tests":[{"expectedStdout":"(42,)"},{"setup":"# hidden check","expectedStdout":"(42,)"}]}'::jsonb),
  ('m6-t2-p06', '{"tests":[{"expectedStdout":"(1, 2, 3)"},{"setup":"# hidden check","expectedStdout":"(1, 2, 3)"}]}'::jsonb),
  ('m6-t2-p07', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m6-t3-p01', '{"tests":[{"expectedStdout":"[1, 2, 3]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3]"}]}'::jsonb),
  ('m6-t3-p02', '{"tests":[{"expectedStdout":"b"},{"setup":"# hidden check","expectedStdout":"b"}]}'::jsonb),
  ('m6-t3-p03', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m6-t3-p04', '{"tests":[{"expectedStdout":"4"},{"setup":"# hidden check","expectedStdout":"4"}]}'::jsonb),
  ('m6-t3-p05', '{"tests":[{"expectedStdout":"(1, 2)"},{"setup":"# hidden check","expectedStdout":"(1, 2)"}]}'::jsonb),
  ('m6-t3-p06', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m6-t3-p07', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m6-t4-p01', '{"tests":[{"expectedStdout":"[1, 2, 3]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3]"}]}'::jsonb),
  ('m6-t4-p02', '{"tests":[{"expectedStdout":"b"},{"setup":"# hidden check","expectedStdout":"b"}]}'::jsonb),
  ('m6-t4-p03', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m6-t4-p04', '{"tests":[{"expectedStdout":"4"},{"setup":"# hidden check","expectedStdout":"4"}]}'::jsonb),
  ('m6-t4-p05', '{"tests":[{"expectedStdout":"(1, 2)"},{"setup":"# hidden check","expectedStdout":"(1, 2)"}]}'::jsonb),
  ('m6-t4-p06', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m6-t4-p07', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m6-t5-p01', '{"tests":[{"expectedStdout":"[1, 2, 3]"},{"setup":"# hidden check","expectedStdout":"[1, 2, 3]"}]}'::jsonb),
  ('m6-t5-p02', '{"tests":[{"expectedStdout":"b"},{"setup":"# hidden check","expectedStdout":"b"}]}'::jsonb),
  ('m6-t5-p03', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m6-t5-p04', '{"tests":[{"expectedStdout":"4"},{"setup":"# hidden check","expectedStdout":"4"}]}'::jsonb),
  ('m6-t5-p05', '{"tests":[{"expectedStdout":"(1, 2)"},{"setup":"# hidden check","expectedStdout":"(1, 2)"}]}'::jsonb),
  ('m6-t5-p06', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m6-t5-p07', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m7-t1-p01', '{"tests":[{"expectedStdout":"{1, 2, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 2, 3}"}]}'::jsonb),
  ('m7-t1-p02', '{"tests":[{"expectedStdout":"{1, 2, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 2, 3}"}]}'::jsonb),
  ('m7-t1-p03', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m7-t1-p04', '{"tests":[{"expectedStdout":"0"},{"setup":"# hidden check","expectedStdout":"0"}]}'::jsonb),
  ('m7-t1-p05', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m7-t1-p06', '{"tests":[{"expectedStdout":"{''a'', 1}"},{"setup":"# hidden check","expectedStdout":"{''a'', 1}"}]}'::jsonb),
  ('m7-t1-p07', '{"tests":[{"expectedStdout":"{''h'', ''e'', ''l'', ''o''}"},{"setup":"# hidden check","expectedStdout":"{''h'', ''e'', ''l'', ''o''}"}]}'::jsonb),
  ('m7-t2-p01', '{"tests":[{"expectedStdout":"{1, 2}"},{"setup":"# hidden check","expectedStdout":"{1, 2}"}]}'::jsonb),
  ('m7-t2-p02', '{"tests":[{"expectedStdout":"{1, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 3}"}]}'::jsonb),
  ('m7-t2-p03', '{"tests":[{"expectedStdout":"{1, 2}"},{"setup":"# hidden check","expectedStdout":"{1, 2}"}]}'::jsonb),
  ('m7-t2-p04', '{"tests":[{"expectedStdout":"{1, 2, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 2, 3}"}]}'::jsonb),
  ('m7-t2-p05', '{"tests":[{"expectedStdout":"1"},{"setup":"# hidden check","expectedStdout":"1"}]}'::jsonb),
  ('m7-t2-p06', '{"tests":[{"expectedStdout":"set()"},{"setup":"# hidden check","expectedStdout":"set()"}]}'::jsonb),
  ('m7-t2-p07', '{"tests":[{"expectedStdout":"{1, 2}"},{"setup":"# hidden check","expectedStdout":"{1, 2}"}]}'::jsonb),
  ('m7-t3-p01', '{"tests":[{"expectedStdout":"{1, 2, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 2, 3}"}]}'::jsonb),
  ('m7-t3-p02', '{"tests":[{"expectedStdout":"{2, 3}"},{"setup":"# hidden check","expectedStdout":"{2, 3}"}]}'::jsonb),
  ('m7-t3-p03', '{"tests":[{"expectedStdout":"{1, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 3}"}]}'::jsonb),
  ('m7-t3-p04', '{"tests":[{"expectedStdout":"{1, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 3}"}]}'::jsonb),
  ('m7-t3-p05', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m7-t3-p06', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m7-t3-p07', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m7-t4-p01', '{"tests":[{"expectedStdout":"{1, 2, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 2, 3}"}]}'::jsonb),
  ('m7-t4-p02', '{"tests":[{"expectedStdout":"{2, 3}"},{"setup":"# hidden check","expectedStdout":"{2, 3}"}]}'::jsonb),
  ('m7-t4-p03', '{"tests":[{"expectedStdout":"{1, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 3}"}]}'::jsonb),
  ('m7-t4-p04', '{"tests":[{"expectedStdout":"{1, 3}"},{"setup":"# hidden check","expectedStdout":"{1, 3}"}]}'::jsonb),
  ('m7-t4-p05', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m7-t4-p06', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m7-t4-p07', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m8-t1-p01', '{"tests":[{"expectedStdout":"Ana"},{"setup":"# hidden check","expectedStdout":"Ana"}]}'::jsonb),
  ('m8-t1-p02', '{"tests":[{"expectedStdout":"0"},{"setup":"# hidden check","expectedStdout":"0"}]}'::jsonb),
  ('m8-t1-p03', '{"tests":[{"expectedStdout":"Bob"},{"setup":"# hidden check","expectedStdout":"Bob"}]}'::jsonb),
  ('m8-t1-p04', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m8-t1-p05', '{"tests":[{"expectedStdout":"Kim"},{"setup":"# hidden check","expectedStdout":"Kim"}]}'::jsonb),
  ('m8-t1-p06', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m8-t1-p07', '{"tests":[{"expectedStdout":"2"},{"setup":"# hidden check","expectedStdout":"2"}]}'::jsonb),
  ('m8-t2-p01', '{"tests":[{"expectedStdout":"[''a'', ''b'']"},{"setup":"# hidden check","expectedStdout":"[''a'', ''b'']"}]}'::jsonb),
  ('m8-t2-p02', '{"tests":[{"expectedStdout":"[1, 2]"},{"setup":"# hidden check","expectedStdout":"[1, 2]"}]}'::jsonb),
  ('m8-t2-p03', '{"tests":[{"expectedStdout":"[(''x'', 1)]"},{"setup":"# hidden check","expectedStdout":"[(''x'', 1)]"}]}'::jsonb),
  ('m8-t2-p04', '{"tests":[{"expectedStdout":"0"},{"setup":"# hidden check","expectedStdout":"0"}]}'::jsonb),
  ('m8-t2-p05', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m8-t2-p06', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m8-t2-p07', '{"tests":[{"expectedStdout":"Python"},{"setup":"# hidden check","expectedStdout":"Python"}]}'::jsonb),
  ('m8-t3-p01', '{"tests":[{"expectedStdout":"[''a'', ''b'']"},{"setup":"# hidden check","expectedStdout":"[''a'', ''b'']"}]}'::jsonb),
  ('m8-t3-p02', '{"tests":[{"expectedStdout":"[1, 2]"},{"setup":"# hidden check","expectedStdout":"[1, 2]"}]}'::jsonb),
  ('m8-t3-p03', '{"tests":[{"expectedStdout":"[(''x'', 1)]"},{"setup":"# hidden check","expectedStdout":"[(''x'', 1)]"}]}'::jsonb),
  ('m8-t3-p04', '{"tests":[{"expectedStdout":"0"},{"setup":"# hidden check","expectedStdout":"0"}]}'::jsonb),
  ('m8-t3-p05', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m8-t3-p06', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m8-t3-p07', '{"tests":[{"expectedStdout":"Python"},{"setup":"# hidden check","expectedStdout":"Python"}]}'::jsonb),
  ('m8-t4-p01', '{"tests":[{"expectedStdout":"[''a'', ''b'']"},{"setup":"# hidden check","expectedStdout":"[''a'', ''b'']"}]}'::jsonb),
  ('m8-t4-p02', '{"tests":[{"expectedStdout":"[1, 2]"},{"setup":"# hidden check","expectedStdout":"[1, 2]"}]}'::jsonb),
  ('m8-t4-p03', '{"tests":[{"expectedStdout":"[(''x'', 1)]"},{"setup":"# hidden check","expectedStdout":"[(''x'', 1)]"}]}'::jsonb),
  ('m8-t4-p04', '{"tests":[{"expectedStdout":"0"},{"setup":"# hidden check","expectedStdout":"0"}]}'::jsonb),
  ('m8-t4-p05', '{"tests":[{"expectedStdout":"True"},{"setup":"# hidden check","expectedStdout":"True"}]}'::jsonb),
  ('m8-t4-p06', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m8-t4-p07', '{"tests":[{"expectedStdout":"Python"},{"setup":"# hidden check","expectedStdout":"Python"}]}'::jsonb),
  ('m9-t1-p01', '{"tests":[{"expectedStdout":"yes"},{"setup":"# hidden check","expectedStdout":"yes"}]}'::jsonb),
  ('m9-t1-p02', '{"tests":[{"expectedStdout":"done"},{"setup":"# hidden check","expectedStdout":"done"}]}'::jsonb),
  ('m9-t1-p03', '{"tests":[{"expectedStdout":"zero"},{"setup":"# hidden check","expectedStdout":"zero"}]}'::jsonb),
  ('m9-t1-p04', '{"tests":[{"expectedStdout":"Pass"},{"setup":"# hidden check","expectedStdout":"Pass"}]}'::jsonb),
  ('m9-t1-p05', '{"tests":[{"expectedStdout":"Hello"},{"setup":"# hidden check","expectedStdout":"Hello"}]}'::jsonb),
  ('m9-t1-p06', '{"tests":[{"expectedStdout":"ok"},{"setup":"# hidden check","expectedStdout":"ok"}]}'::jsonb),
  ('m9-t1-p07', '{"tests":[{"expectedStdout":"has items"},{"setup":"# hidden check","expectedStdout":"has items"}]}'::jsonb),
  ('m9-t2-p01', '{"tests":[{"expectedStdout":"Pass"},{"setup":"# hidden check","expectedStdout":"Pass"}]}'::jsonb),
  ('m9-t2-p02', '{"tests":[{"expectedStdout":"even"},{"setup":"# hidden check","expectedStdout":"even"}]}'::jsonb),
  ('m9-t2-p03', '{"tests":[{"expectedStdout":"a wins"},{"setup":"# hidden check","expectedStdout":"a wins"}]}'::jsonb),
  ('m9-t2-p04', '{"tests":[{"expectedStdout":"neg"},{"setup":"# hidden check","expectedStdout":"neg"}]}'::jsonb),
  ('m9-t2-p05', '{"tests":[{"expectedStdout":"empty"},{"setup":"# hidden check","expectedStdout":"empty"}]}'::jsonb),
  ('m9-t2-p06', '{"tests":[{"expectedStdout":"positive"},{"setup":"# hidden check","expectedStdout":"positive"}]}'::jsonb),
  ('m9-t2-p07', '{"tests":[{"expectedStdout":"welcome"},{"setup":"# hidden check","expectedStdout":"welcome"}]}'::jsonb),
  ('m9-t3-p01', '{"tests":[{"expectedStdout":"A"},{"setup":"# hidden check","expectedStdout":"A"}]}'::jsonb),
  ('m9-t3-p02', '{"tests":[{"expectedStdout":"B"},{"setup":"# hidden check","expectedStdout":"B"}]}'::jsonb),
  ('m9-t3-p03', '{"tests":[{"expectedStdout":"C"},{"setup":"# hidden check","expectedStdout":"C"}]}'::jsonb),
  ('m9-t3-p04', '{"tests":[{"expectedStdout":"warm"},{"setup":"# hidden check","expectedStdout":"warm"}]}'::jsonb),
  ('m9-t3-p05', '{"tests":[{"expectedStdout":"zero"},{"setup":"# hidden check","expectedStdout":"zero"}]}'::jsonb),
  ('m9-t3-p06', '{"tests":[{"expectedStdout":"warning"},{"setup":"# hidden check","expectedStdout":"warning"}]}'::jsonb),
  ('m9-t3-p07', '{"tests":[{"expectedStdout":"view"},{"setup":"# hidden check","expectedStdout":"view"}]}'::jsonb),
  ('m10-t1-p01', '{"tests":[{"expectedStdout":"1\n2\n3"},{"setup":"# hidden check","expectedStdout":"1\n2\n3"}]}'::jsonb),
  ('m10-t1-p02', '{"tests":[{"expectedStdout":"15"},{"setup":"# hidden check","expectedStdout":"15"}]}'::jsonb),
  ('m10-t1-p03', '{"tests":[{"expectedStdout":"3\n2\n1"},{"setup":"# hidden check","expectedStdout":"3\n2\n1"}]}'::jsonb),
  ('m10-t1-p04', '{"tests":[{"expectedStdout":"1\n2"},{"setup":"# hidden check","expectedStdout":"1\n2"}]}'::jsonb),
  ('m10-t1-p05', '{"tests":[{"expectedStdout":"tick\ntick\ntick"},{"setup":"# hidden check","expectedStdout":"tick\ntick\ntick"}]}'::jsonb),
  ('m10-t1-p06', '{"tests":[{"expectedStdout":"24"},{"setup":"# hidden check","expectedStdout":"24"}]}'::jsonb),
  ('m10-t1-p07', '{"tests":[{"expectedStdout":"0\n1\n2"},{"setup":"# hidden check","expectedStdout":"0\n1\n2"}]}'::jsonb),
  ('m10-t2-p01', '{"tests":[{"expectedStdout":"1\n2\n3"},{"setup":"# hidden check","expectedStdout":"1\n2\n3"}]}'::jsonb),
  ('m10-t2-p02', '{"tests":[{"expectedStdout":"a\nb\nc"},{"setup":"# hidden check","expectedStdout":"a\nb\nc"}]}'::jsonb),
  ('m10-t2-p03', '{"tests":[{"expectedStdout":"h\ni"},{"setup":"# hidden check","expectedStdout":"h\ni"}]}'::jsonb),
  ('m10-t2-p04', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m10-t2-p05', '{"tests":[{"expectedStdout":"0:x\n1:y"},{"setup":"# hidden check","expectedStdout":"0:x\n1:y"}]}'::jsonb),
  ('m10-t2-p06', '{"tests":[{"expectedStdout":"1\n2\n1\n2"},{"setup":"# hidden check","expectedStdout":"1\n2\n1\n2"}]}'::jsonb),
  ('m10-t2-p07', '{"tests":[{"expectedStdout":"1\n2\n3"},{"setup":"# hidden check","expectedStdout":"1\n2\n3"}]}'::jsonb),
  ('m10-t3-p01', '{"tests":[{"expectedStdout":"1\n2"},{"setup":"# hidden check","expectedStdout":"1\n2"}]}'::jsonb),
  ('m10-t3-p02', '{"tests":[{"expectedStdout":"1\n3\n4"},{"setup":"# hidden check","expectedStdout":"1\n3\n4"}]}'::jsonb),
  ('m10-t3-p03', '{"tests":[{"expectedStdout":"found"},{"setup":"# hidden check","expectedStdout":"found"}]}'::jsonb),
  ('m10-t3-p04', '{"tests":[{"expectedStdout":"2\n4"},{"setup":"# hidden check","expectedStdout":"2\n4"}]}'::jsonb),
  ('m10-t3-p05', '{"tests":[{"expectedStdout":"1\n2"},{"setup":"# hidden check","expectedStdout":"1\n2"}]}'::jsonb),
  ('m10-t3-p06', '{"tests":[{"expectedStdout":"a\nb"},{"setup":"# hidden check","expectedStdout":"a\nb"}]}'::jsonb),
  ('m10-t3-p07', '{"tests":[{"expectedStdout":"1\n1\n2"},{"setup":"# hidden check","expectedStdout":"1\n1\n2"}]}'::jsonb),
  ('m10-t4-p01', '{"tests":[{"expectedStdout":"ok"},{"setup":"# hidden check","expectedStdout":"ok"}]}'::jsonb),
  ('m10-t4-p02', '{"tests":[{"expectedStdout":"done"},{"setup":"# hidden check","expectedStdout":"done"}]}'::jsonb),
  ('m10-t4-p03', '{"tests":[{"expectedStdout":"finished"},{"setup":"# hidden check","expectedStdout":"finished"}]}'::jsonb),
  ('m10-t4-p04', '{"tests":[{"expectedStdout":"called"},{"setup":"# hidden check","expectedStdout":"called"}]}'::jsonb),
  ('m10-t4-p05', '{"tests":[{"expectedStdout":"ready"},{"setup":"# hidden check","expectedStdout":"ready"}]}'::jsonb),
  ('m10-t4-p06', '{"tests":[{"expectedStdout":"safe"},{"setup":"# hidden check","expectedStdout":"safe"}]}'::jsonb),
  ('m10-t4-p07', '{"tests":[{"expectedStdout":"stubs"},{"setup":"# hidden check","expectedStdout":"stubs"}]}'::jsonb),
  ('m10-t5-p01', '{"tests":[{"expectedStdout":"[0, 1, 2, 3, 4]"},{"setup":"# hidden check","expectedStdout":"[0, 1, 2, 3, 4]"}]}'::jsonb),
  ('m10-t5-p02', '{"tests":[{"expectedStdout":"[2, 3, 4, 5]"},{"setup":"# hidden check","expectedStdout":"[2, 3, 4, 5]"}]}'::jsonb),
  ('m10-t5-p03', '{"tests":[{"expectedStdout":"[0, 2, 4, 6, 8]"},{"setup":"# hidden check","expectedStdout":"[0, 2, 4, 6, 8]"}]}'::jsonb),
  ('m10-t5-p04', '{"tests":[{"expectedStdout":"1\n2\n3"},{"setup":"# hidden check","expectedStdout":"1\n2\n3"}]}'::jsonb),
  ('m10-t5-p05', '{"tests":[{"expectedStdout":"10\n20\n30"},{"setup":"# hidden check","expectedStdout":"10\n20\n30"}]}'::jsonb),
  ('m10-t5-p06', '{"tests":[{"expectedStdout":"[5, 4, 3, 2, 1]"},{"setup":"# hidden check","expectedStdout":"[5, 4, 3, 2, 1]"}]}'::jsonb),
  ('m10-t5-p07', '{"tests":[{"expectedStdout":"15"},{"setup":"# hidden check","expectedStdout":"15"}]}'::jsonb),
  ('m11-t1-p01', '{"tests":[{"expectedStdout":"[0, 1, 2]"},{"setup":"# hidden check","expectedStdout":"[0, 1, 2]"}]}'::jsonb),
  ('m11-t1-p02', '{"tests":[{"expectedStdout":"[1, 4, 9]"},{"setup":"# hidden check","expectedStdout":"[1, 4, 9]"}]}'::jsonb),
  ('m11-t1-p03', '{"tests":[{"expectedStdout":"[0, 2, 4]"},{"setup":"# hidden check","expectedStdout":"[0, 2, 4]"}]}'::jsonb),
  ('m11-t1-p04', '{"tests":[{"expectedStdout":"[''A'', ''B'']"},{"setup":"# hidden check","expectedStdout":"[''A'', ''B'']"}]}'::jsonb),
  ('m11-t1-p05', '{"tests":[{"expectedStdout":"[0, 1, 0, 1]"},{"setup":"# hidden check","expectedStdout":"[0, 1, 0, 1]"}]}'::jsonb),
  ('m11-t1-p06', '{"tests":[{"expectedStdout":"[2, 3]"},{"setup":"# hidden check","expectedStdout":"[2, 3]"}]}'::jsonb),
  ('m11-t1-p07', '{"tests":[{"expectedStdout":"[-1, 2, -3]"},{"setup":"# hidden check","expectedStdout":"[-1, 2, -3]"}]}'::jsonb),
  ('m11-t2-p01', '{"tests":[{"expectedStdout":"[0, 1, 2]"},{"setup":"# hidden check","expectedStdout":"[0, 1, 2]"}]}'::jsonb),
  ('m11-t2-p02', '{"tests":[{"expectedStdout":"[1, 4, 9]"},{"setup":"# hidden check","expectedStdout":"[1, 4, 9]"}]}'::jsonb),
  ('m11-t2-p03', '{"tests":[{"expectedStdout":"[0, 2, 4]"},{"setup":"# hidden check","expectedStdout":"[0, 2, 4]"}]}'::jsonb),
  ('m11-t2-p04', '{"tests":[{"expectedStdout":"[''A'', ''B'']"},{"setup":"# hidden check","expectedStdout":"[''A'', ''B'']"}]}'::jsonb),
  ('m11-t2-p05', '{"tests":[{"expectedStdout":"[0, 1, 0, 1]"},{"setup":"# hidden check","expectedStdout":"[0, 1, 0, 1]"}]}'::jsonb),
  ('m11-t2-p06', '{"tests":[{"expectedStdout":"[2, 3]"},{"setup":"# hidden check","expectedStdout":"[2, 3]"}]}'::jsonb),
  ('m11-t2-p07', '{"tests":[{"expectedStdout":"[-1, 2, -3]"},{"setup":"# hidden check","expectedStdout":"[-1, 2, -3]"}]}'::jsonb),
  ('m11-t3-p01', '{"tests":[{"expectedStdout":"{0: 0, 1: 2, 2: 4}"},{"setup":"# hidden check","expectedStdout":"{0: 0, 1: 2, 2: 4}"}]}'::jsonb),
  ('m11-t3-p02', '{"tests":[{"expectedStdout":"{''a'': 1, ''ab'': 2}"},{"setup":"# hidden check","expectedStdout":"{''a'': 1, ''ab'': 2}"}]}'::jsonb),
  ('m11-t3-p03', '{"tests":[{"expectedStdout":"{1: 1, 3: 3}"},{"setup":"# hidden check","expectedStdout":"{1: 1, 3: 3}"}]}'::jsonb),
  ('m11-t3-p04', '{"tests":[{"expectedStdout":"{1: ''a'', 2: ''b''}"},{"setup":"# hidden check","expectedStdout":"{1: ''a'', 2: ''b''}"}]}'::jsonb),
  ('m11-t3-p05', '{"tests":[{"expectedStdout":"{''a'': 0, ''b'': 1}"},{"setup":"# hidden check","expectedStdout":"{''a'': 0, ''b'': 1}"}]}'::jsonb),
  ('m11-t3-p06', '{"tests":[{"expectedStdout":"{0: ''even'', 1: ''odd'', 2: ''even''}"},{"setup":"# hidden check","expectedStdout":"{0: ''even'', 1: ''odd'', 2: ''even''}"}]}'::jsonb),
  ('m11-t3-p07', '{"tests":[{"expectedStdout":"{''a'': 1, ''b'': 2}"},{"setup":"# hidden check","expectedStdout":"{''a'': 1, ''b'': 2}"}]}'::jsonb),
  ('m12-t1-p01', '{"tests":[{"expectedStdout":"Hi"},{"setup":"# hidden check","expectedStdout":"Hi"}]}'::jsonb),
  ('m12-t1-p02', '{"tests":[{"expectedStdout":"5"},{"setup":"# hidden check","expectedStdout":"5"}]}'::jsonb),
  ('m12-t1-p03', '{"tests":[{"expectedStdout":"HI"},{"setup":"# hidden check","expectedStdout":"HI"}]}'::jsonb),
  ('m12-t1-p04', '{"tests":[{"expectedStdout":"Hi Guest"},{"setup":"# hidden check","expectedStdout":"Hi Guest"}]}'::jsonb),
  ('m12-t1-p05', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m12-t1-p06', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m12-t1-p07', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m12-t2-p01', '{"tests":[{"expectedStdout":"Hi"},{"setup":"# hidden check","expectedStdout":"Hi"}]}'::jsonb),
  ('m12-t2-p02', '{"tests":[{"expectedStdout":"5"},{"setup":"# hidden check","expectedStdout":"5"}]}'::jsonb),
  ('m12-t2-p03', '{"tests":[{"expectedStdout":"HI"},{"setup":"# hidden check","expectedStdout":"HI"}]}'::jsonb),
  ('m12-t2-p04', '{"tests":[{"expectedStdout":"Hi Guest"},{"setup":"# hidden check","expectedStdout":"Hi Guest"}]}'::jsonb),
  ('m12-t2-p05', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m12-t2-p06', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m12-t2-p07', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m12-t3-p01', '{"tests":[{"expectedStdout":"Hi"},{"setup":"# hidden check","expectedStdout":"Hi"}]}'::jsonb),
  ('m12-t3-p02', '{"tests":[{"expectedStdout":"5"},{"setup":"# hidden check","expectedStdout":"5"}]}'::jsonb),
  ('m12-t3-p03', '{"tests":[{"expectedStdout":"HI"},{"setup":"# hidden check","expectedStdout":"HI"}]}'::jsonb),
  ('m12-t3-p04', '{"tests":[{"expectedStdout":"Hi Guest"},{"setup":"# hidden check","expectedStdout":"Hi Guest"}]}'::jsonb),
  ('m12-t3-p05', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m12-t3-p06', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m12-t3-p07', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m12-t4-p01', '{"tests":[{"expectedStdout":"Hi"},{"setup":"# hidden check","expectedStdout":"Hi"}]}'::jsonb),
  ('m12-t4-p02', '{"tests":[{"expectedStdout":"5"},{"setup":"# hidden check","expectedStdout":"5"}]}'::jsonb),
  ('m12-t4-p03', '{"tests":[{"expectedStdout":"HI"},{"setup":"# hidden check","expectedStdout":"HI"}]}'::jsonb),
  ('m12-t4-p04', '{"tests":[{"expectedStdout":"Hi Guest"},{"setup":"# hidden check","expectedStdout":"Hi Guest"}]}'::jsonb),
  ('m12-t4-p05', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m12-t4-p06', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m12-t4-p07', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m12-t5-p01', '{"tests":[{"expectedStdout":"3\n2\n1"},{"setup":"# hidden check","expectedStdout":"3\n2\n1"}]}'::jsonb),
  ('m12-t5-p02', '{"tests":[{"expectedStdout":"120"},{"setup":"# hidden check","expectedStdout":"120"}]}'::jsonb),
  ('m12-t5-p03', '{"tests":[{"expectedStdout":"15"},{"setup":"# hidden check","expectedStdout":"15"}]}'::jsonb),
  ('m12-t5-p04', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m12-t5-p05', '{"tests":[{"expectedStdout":"8"},{"setup":"# hidden check","expectedStdout":"8"}]}'::jsonb),
  ('m12-t5-p06', '{"tests":[{"expectedStdout":"3"},{"setup":"# hidden check","expectedStdout":"3"}]}'::jsonb),
  ('m12-t5-p07', '{"tests":[{"expectedStdout":"2\n1"},{"setup":"# hidden check","expectedStdout":"2\n1"}]}'::jsonb),
  ('m13-t1-p01', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb),
  ('m13-t1-p02', '{"tests":[{"expectedStdout":"7"},{"setup":"# hidden check","expectedStdout":"7"}]}'::jsonb),
  ('m13-t1-p03', '{"tests":[{"expectedStdout":"16"},{"setup":"# hidden check","expectedStdout":"16"}]}'::jsonb),
  ('m13-t1-p04', '{"tests":[{"expectedStdout":"[2, 4, 6]"},{"setup":"# hidden check","expectedStdout":"[2, 4, 6]"}]}'::jsonb),
  ('m13-t1-p05', '{"tests":[{"expectedStdout":"[3, 4]"},{"setup":"# hidden check","expectedStdout":"[3, 4]"}]}'::jsonb),
  ('m13-t1-p06', '{"tests":[{"expectedStdout":"[''a'', ''bb'', ''ccc'']"},{"setup":"# hidden check","expectedStdout":"[''a'', ''bb'', ''ccc'']"}]}'::jsonb),
  ('m13-t1-p07', '{"tests":[{"expectedStdout":"10"},{"setup":"# hidden check","expectedStdout":"10"}]}'::jsonb)
on conflict (problem_id) do update set tests_json = excluded.tests_json, updated_at = now();