import type { PracticeListItem } from "@/lib/practice-list";

/** Auto-generated by scripts/emit-practice-lists.ts — do not edit by hand. */
export const PAPC_PRACTICE_LIST: PracticeListItem[] = [
  {
    "id": "papc-two-sum",
    "slug": "two-sum",
    "title": "Two-Sum Optimization",
    "difficulty": "medium",
    "order": 1,
    "category": "hash-maps",
    "categoryLabel": "Hash Maps",
    "topicId": "papc"
  },
  {
    "id": "papc-lru-cache",
    "slug": "lru-cache",
    "title": "LRU Cache Implementation",
    "difficulty": "hard",
    "order": 2,
    "category": "hash-maps",
    "categoryLabel": "Hash Maps",
    "topicId": "papc"
  },
  {
    "id": "papc-find-median-data-stream",
    "slug": "find-median-data-stream",
    "title": "Find Median in Data Stream",
    "difficulty": "hard",
    "order": 3,
    "category": "heap",
    "categoryLabel": "Heaps",
    "topicId": "papc"
  },
  {
    "id": "papc-word-ladder",
    "slug": "word-ladder",
    "title": "Word Ladder Transformation",
    "difficulty": "hard",
    "order": 4,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-merge-k-sorted-lists",
    "slug": "merge-k-sorted-lists",
    "title": "Merge k Sorted Lists",
    "difficulty": "hard",
    "order": 5,
    "category": "heap",
    "categoryLabel": "Heaps",
    "topicId": "papc"
  },
  {
    "id": "papc-n-ary-tree-level-order",
    "slug": "n-ary-tree-level-order",
    "title": "N-ary Tree Level Order Traversal",
    "difficulty": "medium",
    "order": 6,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "papc"
  },
  {
    "id": "papc-maximum-product-subarray",
    "slug": "maximum-product-subarray",
    "title": "Maximum Product Subarray",
    "difficulty": "medium",
    "order": 7,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-serialize-deserialize-binary-tree",
    "slug": "serialize-deserialize-binary-tree",
    "title": "Serialize and Deserialize Binary Tree",
    "difficulty": "hard",
    "order": 8,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "papc"
  },
  {
    "id": "papc-largest-rectangle-in-histogram",
    "slug": "largest-rectangle-in-histogram",
    "title": "Largest Rectangle in Histogram",
    "difficulty": "hard",
    "order": 9,
    "category": "stack-queue",
    "categoryLabel": "Stacks & Queues",
    "topicId": "papc"
  },
  {
    "id": "papc-trapping-rain-water",
    "slug": "trapping-rain-water",
    "title": "Trapping Rain Water",
    "difficulty": "hard",
    "order": 10,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-minimum-window-substring",
    "slug": "minimum-window-substring",
    "title": "Minimum Window Substring",
    "difficulty": "hard",
    "order": 11,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-word-break-ii",
    "slug": "word-break-ii",
    "title": "Word Break II",
    "difficulty": "hard",
    "order": 12,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-regular-expression-matching",
    "slug": "regular-expression-matching",
    "title": "Regular Expression Matching",
    "difficulty": "hard",
    "order": 13,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-median-of-two-sorted-arrays",
    "slug": "median-of-two-sorted-arrays",
    "title": "Median of Two Sorted Arrays",
    "difficulty": "hard",
    "order": 14,
    "category": "binary-search",
    "categoryLabel": "Binary Search",
    "topicId": "papc"
  },
  {
    "id": "papc-longest-substring-without-repeating-characters",
    "slug": "longest-substring-without-repeating-characters",
    "title": "Longest Substring Without Repeating Characters",
    "difficulty": "medium",
    "order": 15,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-container-with-most-water",
    "slug": "container-with-most-water",
    "title": "Container With Most Water",
    "difficulty": "medium",
    "order": 16,
    "category": "greedy",
    "categoryLabel": "Greedy",
    "topicId": "papc"
  },
  {
    "id": "papc-reverse-linked-list-ii",
    "slug": "reverse-linked-list-ii",
    "title": "Reverse Linked List II",
    "difficulty": "medium",
    "order": 17,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-remove-duplicates-sorted-array-ii",
    "slug": "remove-duplicates-sorted-array-ii",
    "title": "Remove Duplicates from Sorted Array II",
    "difficulty": "medium",
    "order": 18,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-rotate-array",
    "slug": "rotate-array",
    "title": "Rotate Array",
    "difficulty": "easy",
    "order": 19,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-search-in-rotated-sorted-array",
    "slug": "search-in-rotated-sorted-array",
    "title": "Search in Rotated Sorted Array",
    "difficulty": "medium",
    "order": 20,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-number-of-islands",
    "slug": "number-of-islands",
    "title": "Number of Islands",
    "difficulty": "medium",
    "order": 21,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-course-schedule",
    "slug": "course-schedule",
    "title": "Course Schedule",
    "difficulty": "medium",
    "order": 22,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-decode-ways",
    "slug": "decode-ways",
    "title": "Decode Ways",
    "difficulty": "medium",
    "order": 23,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-palindrome-partitioning",
    "slug": "palindrome-partitioning",
    "title": "Palindrome Partitioning",
    "difficulty": "medium",
    "order": 24,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "papc"
  },
  {
    "id": "papc-clone-graph",
    "slug": "clone-graph",
    "title": "Clone Graph",
    "difficulty": "medium",
    "order": 25,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-gas-station",
    "slug": "gas-station",
    "title": "Gas Station",
    "difficulty": "medium",
    "order": 26,
    "category": "greedy",
    "categoryLabel": "Greedy",
    "topicId": "papc"
  },
  {
    "id": "papc-candy",
    "slug": "candy",
    "title": "Candy Distribution",
    "difficulty": "hard",
    "order": 27,
    "category": "greedy",
    "categoryLabel": "Greedy",
    "topicId": "papc"
  },
  {
    "id": "papc-trapping-rain-water-ii",
    "slug": "trapping-rain-water-ii",
    "title": "Trapping Rain Water II",
    "difficulty": "hard",
    "order": 28,
    "category": "heap",
    "categoryLabel": "Heaps",
    "topicId": "papc"
  },
  {
    "id": "papc-minimum-height-trees",
    "slug": "minimum-height-trees",
    "title": "Minimum Height Trees",
    "difficulty": "medium",
    "order": 29,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-alien-dictionary",
    "slug": "alien-dictionary",
    "title": "Alien Dictionary",
    "difficulty": "hard",
    "order": 30,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-best-time-buy-sell-stock-iii",
    "slug": "best-time-buy-sell-stock-iii",
    "title": "Best Time to Buy and Sell Stock III",
    "difficulty": "hard",
    "order": 31,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-best-time-buy-sell-stock-iv",
    "slug": "best-time-buy-sell-stock-iv",
    "title": "Best Time to Buy and Sell Stock IV",
    "difficulty": "hard",
    "order": 32,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-maximal-rectangle",
    "slug": "maximal-rectangle",
    "title": "Largest Rectangle in Histogram (Dynamic)",
    "difficulty": "hard",
    "order": 33,
    "category": "stack-queue",
    "categoryLabel": "Stacks & Queues",
    "topicId": "papc"
  },
  {
    "id": "papc-shortest-path-in-binary-matrix",
    "slug": "shortest-path-in-binary-matrix",
    "title": "Shortest Path in Binary Matrix",
    "difficulty": "medium",
    "order": 34,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-evaluate-division",
    "slug": "evaluate-division",
    "title": "Evaluate Division",
    "difficulty": "medium",
    "order": 35,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-path-sum-iii",
    "slug": "path-sum-iii",
    "title": "Path Sum III",
    "difficulty": "medium",
    "order": 36,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "papc"
  },
  {
    "id": "papc-reconstruct-itinerary",
    "slug": "reconstruct-itinerary",
    "title": "Reconstruct Itinerary",
    "difficulty": "hard",
    "order": 37,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-accounts-merge",
    "slug": "accounts-merge",
    "title": "Accounts Merge",
    "difficulty": "medium",
    "order": 38,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "papc"
  },
  {
    "id": "papc-smallest-rectangle-enclosing-black-pixels",
    "slug": "smallest-rectangle-enclosing-black-pixels",
    "title": "Smallest Rectangle Enclosing Black Pixels",
    "difficulty": "hard",
    "order": 39,
    "category": "matrices",
    "categoryLabel": "Matrices",
    "topicId": "papc"
  },
  {
    "id": "papc-meeting-rooms-ii",
    "slug": "meeting-rooms-ii",
    "title": "Meeting Rooms II",
    "difficulty": "medium",
    "order": 40,
    "category": "intervals",
    "categoryLabel": "Intervals",
    "topicId": "papc"
  },
  {
    "id": "papc-insert-interval",
    "slug": "insert-interval",
    "title": "Insert Interval",
    "difficulty": "medium",
    "order": 41,
    "category": "intervals",
    "categoryLabel": "Intervals",
    "topicId": "papc"
  },
  {
    "id": "papc-burst-balloons",
    "slug": "burst-balloons",
    "title": "Burst Balloons",
    "difficulty": "hard",
    "order": 42,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-russian-doll-envelopes",
    "slug": "russian-doll-envelopes",
    "title": "Russian Doll Envelopes",
    "difficulty": "hard",
    "order": 43,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-maximal-square",
    "slug": "maximal-square",
    "title": "Maximal Square",
    "difficulty": "medium",
    "order": 44,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-minimum-path-sum",
    "slug": "minimum-path-sum",
    "title": "Minimum Path Sum",
    "difficulty": "medium",
    "order": 45,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-unique-paths-ii",
    "slug": "unique-paths-ii",
    "title": "Unique Paths II",
    "difficulty": "medium",
    "order": 46,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-edit-distance",
    "slug": "edit-distance",
    "title": "Edit Distance",
    "difficulty": "hard",
    "order": 47,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-integer-to-english-words",
    "slug": "integer-to-english-words",
    "title": "Integer to English Words",
    "difficulty": "hard",
    "order": 48,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-reorder-data-in-log-files",
    "slug": "reorder-data-in-log-files",
    "title": "Reorder Data in Log Files",
    "difficulty": "medium",
    "order": 49,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-longest-increasing-subsequence",
    "slug": "longest-increasing-subsequence",
    "title": "Longest Increasing Subsequence",
    "difficulty": "medium",
    "order": 50,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-two-sum-ii",
    "slug": "two-sum-ii",
    "title": "Two Sum II — Input Array Is Sorted",
    "difficulty": "easy",
    "order": 51,
    "category": "hash-maps",
    "categoryLabel": "Hash Maps",
    "topicId": "papc"
  },
  {
    "id": "papc-three-sum",
    "slug": "three-sum",
    "title": "3Sum",
    "difficulty": "medium",
    "order": 52,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-coin-change",
    "slug": "coin-change",
    "title": "Coin Change",
    "difficulty": "medium",
    "order": 53,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-binary-tree-level-order-traversal",
    "slug": "binary-tree-level-order-traversal",
    "title": "Binary Tree Level Order Traversal",
    "difficulty": "medium",
    "order": 54,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "papc"
  },
  {
    "id": "papc-lowest-common-ancestor-of-a-binary-tree",
    "slug": "lowest-common-ancestor-of-a-binary-tree",
    "title": "Lowest Common Ancestor of a Binary Tree",
    "difficulty": "medium",
    "order": 55,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "papc"
  },
  {
    "id": "papc-reverse-integer",
    "slug": "reverse-integer",
    "title": "Reverse Integer",
    "difficulty": "medium",
    "order": 56,
    "category": "bit-manipulation",
    "categoryLabel": "Bit Manipulation",
    "topicId": "papc"
  },
  {
    "id": "papc-integer-to-roman",
    "slug": "integer-to-roman",
    "title": "Integer to Roman",
    "difficulty": "medium",
    "order": 57,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-combination-sum",
    "slug": "combination-sum",
    "title": "Combination Sum",
    "difficulty": "medium",
    "order": 58,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "papc"
  },
  {
    "id": "papc-permutations",
    "slug": "permutations",
    "title": "Permutations",
    "difficulty": "medium",
    "order": 59,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "papc"
  },
  {
    "id": "papc-n-queens",
    "slug": "n-queens",
    "title": "N-Queens",
    "difficulty": "hard",
    "order": 60,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "papc"
  },
  {
    "id": "papc-implement-trie",
    "slug": "implement-trie",
    "title": "Implement Trie (Prefix Tree)",
    "difficulty": "medium",
    "order": 61,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-word-search-ii",
    "slug": "word-search-ii",
    "title": "Word Search II",
    "difficulty": "hard",
    "order": 62,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "papc"
  },
  {
    "id": "papc-intersection-of-two-linked-lists",
    "slug": "intersection-of-two-linked-lists",
    "title": "Intersection of Two Linked Lists",
    "difficulty": "easy",
    "order": 63,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-majority-element",
    "slug": "majority-element",
    "title": "Majority Element",
    "difficulty": "easy",
    "order": 64,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-product-of-array-except-self",
    "slug": "product-of-array-except-self",
    "title": "Product of Array Except Self",
    "difficulty": "medium",
    "order": 65,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-first-missing-positive",
    "slug": "first-missing-positive",
    "title": "First Missing Positive",
    "difficulty": "hard",
    "order": 66,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "papc"
  },
  {
    "id": "papc-kth-largest-element-in-an-array",
    "slug": "kth-largest-element-in-an-array",
    "title": "Kth Largest Element in an Array",
    "difficulty": "medium",
    "order": 67,
    "category": "heap",
    "categoryLabel": "Heaps",
    "topicId": "papc"
  },
  {
    "id": "papc-valid-palindrome",
    "slug": "valid-palindrome",
    "title": "Valid Palindrome",
    "difficulty": "easy",
    "order": 68,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-longest-common-prefix",
    "slug": "longest-common-prefix",
    "title": "Longest Common Prefix",
    "difficulty": "easy",
    "order": 69,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-group-anagrams",
    "slug": "group-anagrams",
    "title": "Group Anagrams",
    "difficulty": "medium",
    "order": 70,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-isomorphic-strings",
    "slug": "isomorphic-strings",
    "title": "Isomorphic Strings",
    "difficulty": "easy",
    "order": 71,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "papc"
  },
  {
    "id": "papc-different-ways-to-add-parentheses",
    "slug": "different-ways-to-add-parentheses",
    "title": "Different Ways to Add Parentheses",
    "difficulty": "medium",
    "order": 72,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-wildcard-matching",
    "slug": "wildcard-matching",
    "title": "Wildcard Matching",
    "difficulty": "hard",
    "order": 73,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "papc"
  },
  {
    "id": "papc-sum-of-two-integers",
    "slug": "sum-of-two-integers",
    "title": "Sum of Two Integers",
    "difficulty": "easy",
    "order": 74,
    "category": "bit-manipulation",
    "categoryLabel": "Bit Manipulation",
    "topicId": "papc"
  },
  {
    "id": "papc-fraction-to-recurring-decimal",
    "slug": "fraction-to-recurring-decimal",
    "title": "Fraction to Recurring Decimal",
    "difficulty": "hard",
    "order": 75,
    "category": "hash-maps",
    "categoryLabel": "Hash Maps",
    "topicId": "papc"
  }
];
