import type { PracticeListItem } from "@/lib/practice-list";

/** Auto-generated by scripts/emit-practice-lists.ts — do not edit by hand. */
export const PYTHON_PROGRAMMING_LIST: PracticeListItem[] = [
  {
    "id": "pb-hello-name",
    "slug": "hello-name",
    "title": "Hello, Name",
    "difficulty": "easy",
    "order": 1,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-variable-assignment",
    "slug": "variable-assignment",
    "title": "Variable Assignment",
    "difficulty": "easy",
    "order": 2,
    "category": "variables",
    "categoryLabel": "Variables",
    "topicId": "pb-variables"
  },
  {
    "id": "pb-string-manipulation",
    "slug": "string-manipulation",
    "title": "String Manipulation",
    "difficulty": "easy",
    "order": 3,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-mathematical-operations",
    "slug": "mathematical-operations",
    "title": "Mathematical Operations",
    "difficulty": "easy",
    "order": 4,
    "category": "numbers",
    "categoryLabel": "Numbers",
    "topicId": "pb-numbers"
  },
  {
    "id": "pb-list-operations",
    "slug": "list-operations",
    "title": "List Operations",
    "difficulty": "easy",
    "order": 5,
    "category": "lists",
    "categoryLabel": "Lists",
    "topicId": "pb-lists"
  },
  {
    "id": "pb-tuples-and-unpacking",
    "slug": "tuples-and-unpacking",
    "title": "Tuples and Unpacking",
    "difficulty": "easy",
    "order": 6,
    "category": "tuples",
    "categoryLabel": "Tuples",
    "topicId": "pb-tuples"
  },
  {
    "id": "pb-dictionary-operations",
    "slug": "dictionary-operations",
    "title": "Dictionary Operations",
    "difficulty": "easy",
    "order": 7,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-set-operations",
    "slug": "set-operations",
    "title": "Set Operations",
    "difficulty": "easy",
    "order": 8,
    "category": "sets",
    "categoryLabel": "Sets",
    "topicId": "pb-sets"
  },
  {
    "id": "pb-restaurant-bill",
    "slug": "restaurant-bill",
    "title": "Restaurant Bill",
    "difficulty": "easy",
    "order": 9,
    "category": "operators",
    "categoryLabel": "Operators",
    "topicId": "pb-operators"
  },
  {
    "id": "pb-temperature-label",
    "slug": "temperature-label",
    "title": "Temperature Label",
    "difficulty": "easy",
    "order": 10,
    "category": "conditionals",
    "categoryLabel": "Conditionals",
    "topicId": "pb-conditionals"
  },
  {
    "id": "pb-loan-eligibility",
    "slug": "loan-eligibility",
    "title": "Loan Eligibility",
    "difficulty": "easy",
    "order": 11,
    "category": "conditionals",
    "categoryLabel": "Conditionals",
    "topicId": "pb-conditionals"
  },
  {
    "id": "pb-multiplication-table",
    "slug": "multiplication-table",
    "title": "Multiplication Table",
    "difficulty": "easy",
    "order": 12,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-sum-of-evens",
    "slug": "sum-of-evens",
    "title": "Sum of Even Numbers",
    "difficulty": "easy",
    "order": 13,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-until-quit",
    "slug": "until-quit",
    "title": "Loop Until Quit",
    "difficulty": "easy",
    "order": 14,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-factorial",
    "slug": "factorial",
    "title": "Factorial Function",
    "difficulty": "easy",
    "order": 15,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-membership-check",
    "slug": "membership-check",
    "title": "Membership Check",
    "difficulty": "easy",
    "order": 16,
    "category": "operators",
    "categoryLabel": "Operators",
    "topicId": "pb-operators"
  },
  {
    "id": "pb-letter-grade",
    "slug": "letter-grade",
    "title": "Letter Grade",
    "difficulty": "easy",
    "order": 17,
    "category": "conditionals",
    "categoryLabel": "Conditionals",
    "topicId": "pb-conditionals"
  },
  {
    "id": "pb-store-city",
    "slug": "store-city",
    "title": "Store City and Country",
    "difficulty": "easy",
    "order": 18,
    "category": "variables",
    "categoryLabel": "Variables",
    "topicId": "pb-variables"
  },
  {
    "id": "pb-swap-values",
    "slug": "swap-values",
    "title": "Swap Two Values",
    "difficulty": "easy",
    "order": 19,
    "category": "variables",
    "categoryLabel": "Variables",
    "topicId": "pb-variables"
  },
  {
    "id": "pb-circle-area",
    "slug": "circle-area",
    "title": "Circle Area",
    "difficulty": "easy",
    "order": 20,
    "category": "variables",
    "categoryLabel": "Variables",
    "topicId": "pb-variables"
  },
  {
    "id": "pb-full-name",
    "slug": "full-name",
    "title": "Build a Full Name",
    "difficulty": "easy",
    "order": 21,
    "category": "variables",
    "categoryLabel": "Variables",
    "topicId": "pb-variables"
  },
  {
    "id": "pb-value-and-type",
    "slug": "value-and-type",
    "title": "Value and Type",
    "difficulty": "easy",
    "order": 22,
    "category": "variables",
    "categoryLabel": "Variables",
    "topicId": "pb-variables"
  },
  {
    "id": "pb-greeting-fstring",
    "slug": "greeting-fstring",
    "title": "Greeting with f-string",
    "difficulty": "easy",
    "order": 23,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-word-length",
    "slug": "word-length",
    "title": "Word Length",
    "difficulty": "easy",
    "order": 24,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-slice-username",
    "slug": "slice-username",
    "title": "Slice a Username",
    "difficulty": "easy",
    "order": 25,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-replace-hyphens",
    "slug": "replace-hyphens",
    "title": "Replace Spaces with Hyphens",
    "difficulty": "easy",
    "order": 26,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-middle-character",
    "slug": "middle-character",
    "title": "Middle Character",
    "difficulty": "easy",
    "order": 27,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-average-three",
    "slug": "average-three",
    "title": "Average of Three Numbers",
    "difficulty": "easy",
    "order": 28,
    "category": "numbers",
    "categoryLabel": "Numbers",
    "topicId": "pb-numbers"
  },
  {
    "id": "pb-power-calculation",
    "slug": "power-calculation",
    "title": "Power Calculation",
    "difficulty": "easy",
    "order": 29,
    "category": "numbers",
    "categoryLabel": "Numbers",
    "topicId": "pb-numbers"
  },
  {
    "id": "pb-round-price",
    "slug": "round-price",
    "title": "Round a Price",
    "difficulty": "easy",
    "order": 30,
    "category": "numbers",
    "categoryLabel": "Numbers",
    "topicId": "pb-numbers"
  },
  {
    "id": "pb-abs-difference",
    "slug": "abs-difference",
    "title": "Absolute Difference",
    "difficulty": "easy",
    "order": 31,
    "category": "numbers",
    "categoryLabel": "Numbers",
    "topicId": "pb-numbers"
  },
  {
    "id": "pb-integer-division-chain",
    "slug": "integer-division-chain",
    "title": "Integer Division Chain",
    "difficulty": "easy",
    "order": 32,
    "category": "numbers",
    "categoryLabel": "Numbers",
    "topicId": "pb-numbers"
  },
  {
    "id": "pb-list-endpoints",
    "slug": "list-endpoints",
    "title": "List First and Last",
    "difficulty": "easy",
    "order": 33,
    "category": "lists",
    "categoryLabel": "Lists",
    "topicId": "pb-lists"
  },
  {
    "id": "pb-list-pop-append",
    "slug": "list-pop-append",
    "title": "Pop and Append",
    "difficulty": "easy",
    "order": 34,
    "category": "lists",
    "categoryLabel": "Lists",
    "topicId": "pb-lists"
  },
  {
    "id": "pb-list-middle-slice",
    "slug": "list-middle-slice",
    "title": "Middle Slice",
    "difficulty": "easy",
    "order": 35,
    "category": "lists",
    "categoryLabel": "Lists",
    "topicId": "pb-lists"
  },
  {
    "id": "pb-list-count-apples",
    "slug": "list-count-apples",
    "title": "Count Apples",
    "difficulty": "easy",
    "order": 36,
    "category": "lists",
    "categoryLabel": "Lists",
    "topicId": "pb-lists"
  },
  {
    "id": "pb-list-extend-merge",
    "slug": "list-extend-merge",
    "title": "Extend Two Lists",
    "difficulty": "easy",
    "order": 37,
    "category": "lists",
    "categoryLabel": "Lists",
    "topicId": "pb-lists"
  },
  {
    "id": "pb-tuple-second-item",
    "slug": "tuple-second-item",
    "title": "Second Tuple Item",
    "difficulty": "easy",
    "order": 38,
    "category": "tuples",
    "categoryLabel": "Tuples",
    "topicId": "pb-tuples"
  },
  {
    "id": "pb-tuple-count-twos",
    "slug": "tuple-count-twos",
    "title": "Count Twos in Tuple",
    "difficulty": "easy",
    "order": 39,
    "category": "tuples",
    "categoryLabel": "Tuples",
    "topicId": "pb-tuples"
  },
  {
    "id": "pb-tuple-concatenate",
    "slug": "tuple-concatenate",
    "title": "Concatenate Tuples",
    "difficulty": "easy",
    "order": 40,
    "category": "tuples",
    "categoryLabel": "Tuples",
    "topicId": "pb-tuples"
  },
  {
    "id": "pb-tuple-unpack-sum",
    "slug": "tuple-unpack-sum",
    "title": "Unpack and Sum",
    "difficulty": "easy",
    "order": 41,
    "category": "tuples",
    "categoryLabel": "Tuples",
    "topicId": "pb-tuples"
  },
  {
    "id": "pb-dict-get-default",
    "slug": "dict-get-default",
    "title": "Get with Default",
    "difficulty": "easy",
    "order": 42,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-dict-sorted-keys",
    "slug": "dict-sorted-keys",
    "title": "Sorted Dictionary Keys",
    "difficulty": "easy",
    "order": 43,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-dict-add-field",
    "slug": "dict-add-field",
    "title": "Add a Dictionary Field",
    "difficulty": "easy",
    "order": 44,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-dict-values-total",
    "slug": "dict-values-total",
    "title": "Sum Dictionary Values",
    "difficulty": "easy",
    "order": 45,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-set-add-remove",
    "slug": "set-add-remove",
    "title": "Add and Discard",
    "difficulty": "easy",
    "order": 46,
    "category": "sets",
    "categoryLabel": "Sets",
    "topicId": "pb-sets"
  },
  {
    "id": "pb-set-subset-check",
    "slug": "set-subset-check",
    "title": "Subset Check",
    "difficulty": "easy",
    "order": 47,
    "category": "sets",
    "categoryLabel": "Sets",
    "topicId": "pb-sets"
  },
  {
    "id": "pb-set-symmetric-difference",
    "slug": "set-symmetric-difference",
    "title": "Symmetric Difference",
    "difficulty": "easy",
    "order": 48,
    "category": "sets",
    "categoryLabel": "Sets",
    "topicId": "pb-sets"
  },
  {
    "id": "pb-unique-sorted",
    "slug": "unique-sorted",
    "title": "Unique Sorted Values",
    "difficulty": "easy",
    "order": 49,
    "category": "sets",
    "categoryLabel": "Sets",
    "topicId": "pb-sets"
  },
  {
    "id": "pb-even-or-odd",
    "slug": "even-or-odd",
    "title": "Even or Odd",
    "difficulty": "easy",
    "order": 50,
    "category": "operators",
    "categoryLabel": "Operators",
    "topicId": "pb-operators"
  },
  {
    "id": "pb-pick-larger",
    "slug": "pick-larger",
    "title": "Pick the Larger Value",
    "difficulty": "easy",
    "order": 51,
    "category": "operators",
    "categoryLabel": "Operators",
    "topicId": "pb-operators"
  },
  {
    "id": "pb-repeat-laugh",
    "slug": "repeat-laugh",
    "title": "Repeat a String",
    "difficulty": "easy",
    "order": 52,
    "category": "operators",
    "categoryLabel": "Operators",
    "topicId": "pb-operators"
  },
  {
    "id": "pb-password-strength",
    "slug": "password-strength",
    "title": "Password Length Check",
    "difficulty": "easy",
    "order": 53,
    "category": "operators",
    "categoryLabel": "Operators",
    "topicId": "pb-operators"
  },
  {
    "id": "pb-leap-year-label",
    "slug": "leap-year-label",
    "title": "Leap Year Label",
    "difficulty": "easy",
    "order": 54,
    "category": "conditionals",
    "categoryLabel": "Conditionals",
    "topicId": "pb-conditionals"
  },
  {
    "id": "pb-sign-label",
    "slug": "sign-label",
    "title": "Sign Label",
    "difficulty": "easy",
    "order": 55,
    "category": "conditionals",
    "categoryLabel": "Conditionals",
    "topicId": "pb-conditionals"
  },
  {
    "id": "pb-weekend-check",
    "slug": "weekend-check",
    "title": "Weekend Check",
    "difficulty": "easy",
    "order": 56,
    "category": "conditionals",
    "categoryLabel": "Conditionals",
    "topicId": "pb-conditionals"
  },
  {
    "id": "pb-shipping-fee",
    "slug": "shipping-fee",
    "title": "Shipping Fee",
    "difficulty": "easy",
    "order": 57,
    "category": "conditionals",
    "categoryLabel": "Conditionals",
    "topicId": "pb-conditionals"
  },
  {
    "id": "pb-countdown-loop",
    "slug": "countdown-loop",
    "title": "Countdown Loop",
    "difficulty": "easy",
    "order": 58,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-star-row",
    "slug": "star-row",
    "title": "Row of Stars",
    "difficulty": "easy",
    "order": 59,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-squares-one-to-five",
    "slug": "squares-one-to-five",
    "title": "Squares One to Five",
    "difficulty": "easy",
    "order": 60,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-sum-until-zero",
    "slug": "sum-until-zero",
    "title": "Sum Until Zero",
    "difficulty": "easy",
    "order": 61,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-add-two",
    "slug": "add-two",
    "title": "Add Two Numbers",
    "difficulty": "easy",
    "order": 62,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-is-even",
    "slug": "is-even",
    "title": "Is Even",
    "difficulty": "easy",
    "order": 63,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-double-each",
    "slug": "double-each",
    "title": "Double Each Item",
    "difficulty": "easy",
    "order": 64,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-greet-user",
    "slug": "greet-user",
    "title": "Greet User",
    "difficulty": "easy",
    "order": 65,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-max-of-three",
    "slug": "max-of-three",
    "title": "Maximum of Three",
    "difficulty": "easy",
    "order": 66,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-count-vowels",
    "slug": "count-vowels",
    "title": "Count Vowels",
    "difficulty": "easy",
    "order": 67,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-reverse-string-fn",
    "slug": "reverse-string-fn",
    "title": "Reverse a String",
    "difficulty": "easy",
    "order": 68,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-square-number",
    "slug": "square-number",
    "title": "Square a Number",
    "difficulty": "easy",
    "order": 69,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-list-average",
    "slug": "list-average",
    "title": "List Average",
    "difficulty": "easy",
    "order": 70,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-celsius-to-fahrenheit",
    "slug": "celsius-to-fahrenheit",
    "title": "Celsius to Fahrenheit",
    "difficulty": "easy",
    "order": 71,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pc-two-sum",
    "slug": "two-sum",
    "title": "Two Sum",
    "difficulty": "easy",
    "order": 1,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-best-time-to-buy-and-sell-stock",
    "slug": "best-time-to-buy-and-sell-stock",
    "title": "Best Time to Buy and Sell Stock",
    "difficulty": "easy",
    "order": 2,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-contains-duplicate",
    "slug": "contains-duplicate",
    "title": "Contains Duplicate",
    "difficulty": "easy",
    "order": 3,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-valid-anagram",
    "slug": "valid-anagram",
    "title": "Valid Anagram",
    "difficulty": "easy",
    "order": 4,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-remove-duplicates-from-sorted-array",
    "slug": "remove-duplicates-from-sorted-array",
    "title": "Remove Duplicates from Sorted Array",
    "difficulty": "easy",
    "order": 5,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-rotate-array",
    "slug": "rotate-array",
    "title": "Rotate Array",
    "difficulty": "easy",
    "order": 6,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-missing-number",
    "slug": "missing-number",
    "title": "Missing Number",
    "difficulty": "easy",
    "order": 7,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-merge-sorted-array",
    "slug": "merge-sorted-array",
    "title": "Merge Sorted Array",
    "difficulty": "easy",
    "order": 10,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-majority-element",
    "slug": "majority-element",
    "title": "Majority Element",
    "difficulty": "easy",
    "order": 11,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-reverse-string",
    "slug": "reverse-string",
    "title": "Reverse String",
    "difficulty": "easy",
    "order": 16,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-valid-palindrome",
    "slug": "valid-palindrome",
    "title": "Valid Palindrome",
    "difficulty": "easy",
    "order": 17,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-valid-parentheses",
    "slug": "valid-parentheses",
    "title": "Valid Parentheses",
    "difficulty": "easy",
    "order": 21,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-word-pattern",
    "slug": "word-pattern",
    "title": "Word Pattern",
    "difficulty": "easy",
    "order": 22,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-isomorphic-strings",
    "slug": "isomorphic-strings",
    "title": "Isomorphic Strings",
    "difficulty": "easy",
    "order": 23,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-first-unique-character-in-a-string",
    "slug": "first-unique-character-in-a-string",
    "title": "First Unique Character in a String",
    "difficulty": "easy",
    "order": 24,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-reverse-linked-list",
    "slug": "reverse-linked-list",
    "title": "Reverse Linked List",
    "difficulty": "easy",
    "order": 26,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "pc-linked-lists"
  },
  {
    "id": "pc-linked-list-cycle",
    "slug": "linked-list-cycle",
    "title": "Linked List Cycle",
    "difficulty": "easy",
    "order": 27,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "pc-linked-lists"
  },
  {
    "id": "pc-merge-two-sorted-lists",
    "slug": "merge-two-sorted-lists",
    "title": "Merge Two Sorted Lists",
    "difficulty": "easy",
    "order": 29,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "pc-linked-lists"
  },
  {
    "id": "pc-palindrome-linked-list",
    "slug": "palindrome-linked-list",
    "title": "Palindrome Linked List",
    "difficulty": "easy",
    "order": 31,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "pc-linked-lists"
  },
  {
    "id": "pc-implement-queue-using-stacks",
    "slug": "implement-queue-using-stacks",
    "title": "Implement Queue using Stacks",
    "difficulty": "easy",
    "order": 33,
    "category": "stack-queue",
    "categoryLabel": "Stacks & Queues",
    "topicId": "pc-stack-queue"
  },
  {
    "id": "pc-binary-tree-inorder-traversal",
    "slug": "binary-tree-inorder-traversal",
    "title": "Binary Tree Inorder Traversal",
    "difficulty": "easy",
    "order": 37,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-maximum-depth-of-binary-tree",
    "slug": "maximum-depth-of-binary-tree",
    "title": "Maximum Depth of Binary Tree",
    "difficulty": "easy",
    "order": 38,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-same-tree",
    "slug": "same-tree",
    "title": "Same Tree",
    "difficulty": "easy",
    "order": 39,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-invert-binary-tree",
    "slug": "invert-binary-tree",
    "title": "Invert Binary Tree",
    "difficulty": "easy",
    "order": 40,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-balanced-binary-tree",
    "slug": "balanced-binary-tree",
    "title": "Balanced Binary Tree",
    "difficulty": "easy",
    "order": 41,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-lowest-common-ancestor-of-a-bst",
    "slug": "lowest-common-ancestor-of-a-bst",
    "title": "Lowest Common Ancestor of a BST",
    "difficulty": "easy",
    "order": 43,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-climbing-stairs",
    "slug": "climbing-stairs",
    "title": "Climbing Stairs",
    "difficulty": "easy",
    "order": 50,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-two-sum-ii",
    "slug": "two-sum-ii",
    "title": "Two Sum II — Input Array Is Sorted",
    "difficulty": "easy",
    "order": 56,
    "category": "hash-maps",
    "categoryLabel": "Hash Maps",
    "topicId": "pc-hash-maps"
  },
  {
    "id": "pc-binary-search",
    "slug": "binary-search",
    "title": "Binary Search",
    "difficulty": "easy",
    "order": 59,
    "category": "binary-search",
    "categoryLabel": "Binary Search",
    "topicId": "pc-binary-search"
  },
  {
    "id": "pc-assign-cookies",
    "slug": "assign-cookies",
    "title": "Assign Cookies",
    "difficulty": "easy",
    "order": 62,
    "category": "greedy",
    "categoryLabel": "Greedy",
    "topicId": "pc-greedy"
  },
  {
    "id": "pc-single-number",
    "slug": "single-number",
    "title": "Single Number",
    "difficulty": "easy",
    "order": 67,
    "category": "bit-manipulation",
    "categoryLabel": "Bit Manipulation",
    "topicId": "pc-bit-manipulation"
  },
  {
    "id": "pc-power-of-two",
    "slug": "power-of-two",
    "title": "Power of Two",
    "difficulty": "easy",
    "order": 68,
    "category": "bit-manipulation",
    "categoryLabel": "Bit Manipulation",
    "topicId": "pc-bit-manipulation"
  },
  {
    "id": "pc-counting-bits",
    "slug": "counting-bits",
    "title": "Counting Bits",
    "difficulty": "easy",
    "order": 69,
    "category": "bit-manipulation",
    "categoryLabel": "Bit Manipulation",
    "topicId": "pc-bit-manipulation"
  },
  {
    "id": "pc-intersection-of-two-linked-lists",
    "slug": "intersection-of-two-linked-lists",
    "title": "Intersection of Two Linked Lists",
    "difficulty": "easy",
    "order": 93,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "pc-linked-lists"
  },
  {
    "id": "pc-longest-common-prefix",
    "slug": "longest-common-prefix",
    "title": "Longest Common Prefix",
    "difficulty": "easy",
    "order": 94,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-sum-of-two-integers",
    "slug": "sum-of-two-integers",
    "title": "Sum of Two Integers",
    "difficulty": "easy",
    "order": 100,
    "category": "bit-manipulation",
    "categoryLabel": "Bit Manipulation",
    "topicId": "pc-bit-manipulation"
  },
  {
    "id": "pb-average-args",
    "slug": "average-args",
    "title": "Average of Any Count",
    "difficulty": "medium",
    "order": 1,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-lambda-map-filter",
    "slug": "lambda-map-filter",
    "title": "Lambda with Map and Filter",
    "difficulty": "medium",
    "order": 2,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-comprehensions-practice",
    "slug": "comprehensions-practice",
    "title": "List and Dict Comprehensions",
    "difficulty": "medium",
    "order": 3,
    "category": "comprehensions",
    "categoryLabel": "Comprehensions",
    "topicId": "pb-comprehensions"
  },
  {
    "id": "pb-safe-integer-parse",
    "slug": "safe-integer-parse",
    "title": "Safe Integer Parse",
    "difficulty": "medium",
    "order": 4,
    "category": "exceptions",
    "categoryLabel": "Exceptions",
    "topicId": "pb-exceptions"
  },
  {
    "id": "pb-file-number-range",
    "slug": "file-number-range",
    "title": "Write and Read a Number File",
    "difficulty": "medium",
    "order": 5,
    "category": "files",
    "categoryLabel": "Files",
    "topicId": "pb-files"
  },
  {
    "id": "pb-days-until-new-year",
    "slug": "days-until-new-year",
    "title": "Days Until New Year",
    "difficulty": "medium",
    "order": 6,
    "category": "modules",
    "categoryLabel": "Modules",
    "topicId": "pb-modules"
  },
  {
    "id": "pb-bank-account",
    "slug": "bank-account",
    "title": "Bank Account Class",
    "difficulty": "medium",
    "order": 7,
    "category": "oop",
    "categoryLabel": "Classes & OOP",
    "topicId": "pb-oop"
  },
  {
    "id": "pb-product-receipt",
    "slug": "product-receipt",
    "title": "Product Receipt Total",
    "difficulty": "medium",
    "order": 8,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-extract-emails",
    "slug": "extract-emails",
    "title": "Extract Emails",
    "difficulty": "medium",
    "order": 9,
    "category": "regex",
    "categoryLabel": "Regular Expressions",
    "topicId": "pb-regex"
  },
  {
    "id": "pb-student-results",
    "slug": "student-results",
    "title": "Student Results",
    "difficulty": "medium",
    "order": 10,
    "category": "json",
    "categoryLabel": "JSON",
    "topicId": "pb-json"
  },
  {
    "id": "pb-library-system",
    "slug": "library-system",
    "title": "Library System",
    "difficulty": "medium",
    "order": 11,
    "category": "oop",
    "categoryLabel": "Classes & OOP",
    "topicId": "pb-oop"
  },
  {
    "id": "pb-nested-loop-grid",
    "slug": "nested-loop-grid",
    "title": "Multiplication Mini Grid",
    "difficulty": "medium",
    "order": 12,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-enumerate-ranking",
    "slug": "enumerate-ranking",
    "title": "Ranked Standings",
    "difficulty": "medium",
    "order": 13,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-while-collatz",
    "slug": "while-collatz",
    "title": "Collatz Sequence",
    "difficulty": "medium",
    "order": 14,
    "category": "loops",
    "categoryLabel": "Loops",
    "topicId": "pb-loops"
  },
  {
    "id": "pb-operator-precedence",
    "slug": "operator-precedence",
    "title": "Expression Evaluation",
    "difficulty": "medium",
    "order": 15,
    "category": "operators",
    "categoryLabel": "Operators",
    "topicId": "pb-operators"
  },
  {
    "id": "pb-fizzbuzz-range",
    "slug": "fizzbuzz-range",
    "title": "FizzBuzz 1–15",
    "difficulty": "medium",
    "order": 16,
    "category": "conditionals",
    "categoryLabel": "Conditionals",
    "topicId": "pb-conditionals"
  },
  {
    "id": "pb-prime-list-script",
    "slug": "prime-list-script",
    "title": "Primes Up to 30",
    "difficulty": "medium",
    "order": 17,
    "category": "numbers",
    "categoryLabel": "Numbers",
    "topicId": "pb-numbers"
  },
  {
    "id": "pb-running-average-script",
    "slug": "running-average-script",
    "title": "Running Averages",
    "difficulty": "medium",
    "order": 18,
    "category": "numbers",
    "categoryLabel": "Numbers",
    "topicId": "pb-numbers"
  },
  {
    "id": "pb-ascii-table-script",
    "slug": "ascii-table-script",
    "title": "Simple Text Table",
    "difficulty": "medium",
    "order": 19,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-set-report-script",
    "slug": "set-report-script",
    "title": "Set Operations Report",
    "difficulty": "medium",
    "order": 20,
    "category": "sets",
    "categoryLabel": "Sets",
    "topicId": "pb-sets"
  },
  {
    "id": "pb-tuple-unpack-script",
    "slug": "tuple-unpack-script",
    "title": "Coordinate Unpacking",
    "difficulty": "medium",
    "order": 21,
    "category": "tuples",
    "categoryLabel": "Tuples",
    "topicId": "pb-tuples"
  },
  {
    "id": "pb-word-count-script",
    "slug": "word-count-script",
    "title": "Word Frequency Lines",
    "difficulty": "medium",
    "order": 22,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-json-print-script",
    "slug": "json-print-script",
    "title": "Build and Print JSON",
    "difficulty": "medium",
    "order": 23,
    "category": "json",
    "categoryLabel": "JSON",
    "topicId": "pb-json"
  },
  {
    "id": "pb-filter-evens-script",
    "slug": "filter-evens-script",
    "title": "Filter and Double Evens",
    "difficulty": "medium",
    "order": 24,
    "category": "comprehensions",
    "categoryLabel": "Comprehensions",
    "topicId": "pb-comprehensions"
  },
  {
    "id": "pb-score-bands-script",
    "slug": "score-bands-script",
    "title": "Multiple Score Bands",
    "difficulty": "medium",
    "order": 25,
    "category": "conditionals",
    "categoryLabel": "Conditionals",
    "topicId": "pb-conditionals"
  },
  {
    "id": "pb-cycle-remainder-script",
    "slug": "cycle-remainder-script",
    "title": "Day-of-Week Cycle",
    "difficulty": "medium",
    "order": 26,
    "category": "operators",
    "categoryLabel": "Operators",
    "topicId": "pb-operators"
  },
  {
    "id": "pb-keyword-profile",
    "slug": "keyword-profile",
    "title": "Build Profile from Keywords",
    "difficulty": "medium",
    "order": 27,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-default-greeting",
    "slug": "default-greeting",
    "title": "Greeting with Default Title",
    "difficulty": "medium",
    "order": 28,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-merge-word-counts",
    "slug": "merge-word-counts",
    "title": "Merge Word Count Dicts",
    "difficulty": "medium",
    "order": 29,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-parse-csv-fields",
    "slug": "parse-csv-fields",
    "title": "Parse CSV Line",
    "difficulty": "medium",
    "order": 30,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-password-rules",
    "slug": "password-rules",
    "title": "Password Strength Check",
    "difficulty": "medium",
    "order": 31,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-zip-pair-sums",
    "slug": "zip-pair-sums",
    "title": "Pairwise Sums with Zip",
    "difficulty": "medium",
    "order": 32,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-symmetric-difference",
    "slug": "symmetric-difference",
    "title": "Symmetric Difference List",
    "difficulty": "medium",
    "order": 33,
    "category": "sets",
    "categoryLabel": "Sets",
    "topicId": "pb-sets"
  },
  {
    "id": "pb-sort-tuples-by-score",
    "slug": "sort-tuples-by-score",
    "title": "Sort Records by Score",
    "difficulty": "medium",
    "order": 34,
    "category": "tuples",
    "categoryLabel": "Tuples",
    "topicId": "pb-tuples"
  },
  {
    "id": "pb-safe-divide",
    "slug": "safe-divide",
    "title": "Safe Division",
    "difficulty": "medium",
    "order": 35,
    "category": "exceptions",
    "categoryLabel": "Exceptions",
    "topicId": "pb-exceptions"
  },
  {
    "id": "pb-lines-from-text",
    "slug": "lines-from-text",
    "title": "Non-Empty Lines from Text",
    "difficulty": "medium",
    "order": 36,
    "category": "files",
    "categoryLabel": "Files",
    "topicId": "pb-files"
  },
  {
    "id": "pb-stats-with-math",
    "slug": "stats-with-math",
    "title": "Hypotenuse and Rounded Root",
    "difficulty": "medium",
    "order": 37,
    "category": "modules",
    "categoryLabel": "Modules",
    "topicId": "pb-modules"
  },
  {
    "id": "pb-product-class",
    "slug": "product-class",
    "title": "Product Inventory Item",
    "difficulty": "medium",
    "order": 38,
    "category": "oop",
    "categoryLabel": "Classes & OOP",
    "topicId": "pb-oop"
  },
  {
    "id": "pb-merge-json-configs",
    "slug": "merge-json-configs",
    "title": "Merge JSON Config Strings",
    "difficulty": "medium",
    "order": 39,
    "category": "json",
    "categoryLabel": "JSON",
    "topicId": "pb-json"
  },
  {
    "id": "pb-find-phones-lite",
    "slug": "find-phones-lite",
    "title": "Find Phone Numbers",
    "difficulty": "medium",
    "order": 40,
    "category": "regex",
    "categoryLabel": "Regular Expressions",
    "topicId": "pb-regex"
  },
  {
    "id": "pb-comprehension-grid",
    "slug": "comprehension-grid",
    "title": "Build a Number Grid",
    "difficulty": "medium",
    "order": 41,
    "category": "comprehensions",
    "categoryLabel": "Comprehensions",
    "topicId": "pb-comprehensions"
  },
  {
    "id": "pb-rotate-list",
    "slug": "rotate-list",
    "title": "Rotate List Left",
    "difficulty": "medium",
    "order": 42,
    "category": "lists",
    "categoryLabel": "Lists",
    "topicId": "pb-lists"
  },
  {
    "id": "pb-invert-dict-unique",
    "slug": "invert-dict-unique",
    "title": "Invert Unique Mapping",
    "difficulty": "medium",
    "order": 43,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-phrase-palindrome",
    "slug": "phrase-palindrome",
    "title": "Phrase Palindrome Check",
    "difficulty": "medium",
    "order": 44,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pb-strings"
  },
  {
    "id": "pb-nested-get-path",
    "slug": "nested-get-path",
    "title": "Nested Dict Path Lookup",
    "difficulty": "medium",
    "order": 45,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-click-counter-class",
    "slug": "click-counter-class",
    "title": "Click Counter Class",
    "difficulty": "medium",
    "order": 46,
    "category": "oop",
    "categoryLabel": "Classes & OOP",
    "topicId": "pb-oop"
  },
  {
    "id": "pb-parse-int-list",
    "slug": "parse-int-list",
    "title": "Parse Integer List Safely",
    "difficulty": "medium",
    "order": 47,
    "category": "exceptions",
    "categoryLabel": "Exceptions",
    "topicId": "pb-exceptions"
  },
  {
    "id": "pb-group-by-category",
    "slug": "group-by-category",
    "title": "Group Records by Key",
    "difficulty": "medium",
    "order": 48,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-pipeline-transform",
    "slug": "pipeline-transform",
    "title": "Transform Pipeline",
    "difficulty": "medium",
    "order": 49,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-strip-html-tags",
    "slug": "strip-html-tags",
    "title": "Strip Simple HTML Tags",
    "difficulty": "medium",
    "order": 50,
    "category": "regex",
    "categoryLabel": "Regular Expressions",
    "topicId": "pb-regex"
  },
  {
    "id": "pc-product-of-array-except-self",
    "slug": "product-of-array-except-self",
    "title": "Product of Array Except Self",
    "difficulty": "medium",
    "order": 8,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-maximum-subarray",
    "slug": "maximum-subarray",
    "title": "Maximum Subarray",
    "difficulty": "medium",
    "order": 9,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-search-in-rotated-sorted-array",
    "slug": "search-in-rotated-sorted-array",
    "title": "Search in Rotated Sorted Array",
    "difficulty": "medium",
    "order": 13,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-longest-consecutive-sequence",
    "slug": "longest-consecutive-sequence",
    "title": "Longest Consecutive Sequence",
    "difficulty": "medium",
    "order": 14,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-jump-game",
    "slug": "jump-game",
    "title": "Jump Game",
    "difficulty": "medium",
    "order": 15,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-longest-substring-without-repeating-characters",
    "slug": "longest-substring-without-repeating-characters",
    "title": "Longest Substring Without Repeating Characters",
    "difficulty": "medium",
    "order": 18,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-longest-palindromic-substring",
    "slug": "longest-palindromic-substring",
    "title": "Longest Palindromic Substring",
    "difficulty": "medium",
    "order": 19,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-group-anagrams",
    "slug": "group-anagrams",
    "title": "Group Anagrams",
    "difficulty": "medium",
    "order": 20,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-linked-list-cycle-ii",
    "slug": "linked-list-cycle-ii",
    "title": "Linked List Cycle II",
    "difficulty": "medium",
    "order": 28,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "pc-linked-lists"
  },
  {
    "id": "pc-remove-nth-node-from-end-of-list",
    "slug": "remove-nth-node-from-end-of-list",
    "title": "Remove Nth Node From End of List",
    "difficulty": "medium",
    "order": 30,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "pc-linked-lists"
  },
  {
    "id": "pc-reorder-list",
    "slug": "reorder-list",
    "title": "Reorder List",
    "difficulty": "medium",
    "order": 32,
    "category": "linked-lists",
    "categoryLabel": "Linked Lists",
    "topicId": "pc-linked-lists"
  },
  {
    "id": "pc-daily-temperatures",
    "slug": "daily-temperatures",
    "title": "Daily Temperatures",
    "difficulty": "medium",
    "order": 34,
    "category": "stack-queue",
    "categoryLabel": "Stacks & Queues",
    "topicId": "pc-stack-queue"
  },
  {
    "id": "pc-evaluate-reverse-polish-notation",
    "slug": "evaluate-reverse-polish-notation",
    "title": "Evaluate Reverse Polish Notation",
    "difficulty": "medium",
    "order": 35,
    "category": "stack-queue",
    "categoryLabel": "Stacks & Queues",
    "topicId": "pc-stack-queue"
  },
  {
    "id": "pc-binary-tree-level-order-traversal",
    "slug": "binary-tree-level-order-traversal",
    "title": "Binary Tree Level Order Traversal",
    "difficulty": "medium",
    "order": 42,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-number-of-islands",
    "slug": "number-of-islands",
    "title": "Number of Islands",
    "difficulty": "medium",
    "order": 45,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "pc-graphs"
  },
  {
    "id": "pc-clone-graph",
    "slug": "clone-graph",
    "title": "Clone Graph",
    "difficulty": "medium",
    "order": 46,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "pc-graphs"
  },
  {
    "id": "pc-course-schedule",
    "slug": "course-schedule",
    "title": "Course Schedule",
    "difficulty": "medium",
    "order": 47,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "pc-graphs"
  },
  {
    "id": "pc-course-schedule-ii",
    "slug": "course-schedule-ii",
    "title": "Course Schedule II",
    "difficulty": "medium",
    "order": 48,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "pc-graphs"
  },
  {
    "id": "pc-shortest-path-in-binary-matrix",
    "slug": "shortest-path-in-binary-matrix",
    "title": "Shortest Path in Binary Matrix",
    "difficulty": "medium",
    "order": 49,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "pc-graphs"
  },
  {
    "id": "pc-house-robber",
    "slug": "house-robber",
    "title": "House Robber",
    "difficulty": "medium",
    "order": 51,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-coin-change",
    "slug": "coin-change",
    "title": "Coin Change",
    "difficulty": "medium",
    "order": 52,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-longest-increasing-subsequence",
    "slug": "longest-increasing-subsequence",
    "title": "Longest Increasing Subsequence",
    "difficulty": "medium",
    "order": 53,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-zero-one-knapsack",
    "slug": "zero-one-knapsack",
    "title": "0/1 Knapsack",
    "difficulty": "medium",
    "order": 54,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-majority-element-ii",
    "slug": "majority-element-ii",
    "title": "Majority Element II",
    "difficulty": "medium",
    "order": 57,
    "category": "hash-maps",
    "categoryLabel": "Hash Maps",
    "topicId": "pc-hash-maps"
  },
  {
    "id": "pc-random-pick-index",
    "slug": "random-pick-index",
    "title": "Random Pick Index",
    "difficulty": "medium",
    "order": 58,
    "category": "hash-maps",
    "categoryLabel": "Hash Maps",
    "topicId": "pc-hash-maps"
  },
  {
    "id": "pc-find-first-and-last-position",
    "slug": "find-first-and-last-position",
    "title": "Find First and Last Position of Element in Sorted Array",
    "difficulty": "medium",
    "order": 60,
    "category": "binary-search",
    "categoryLabel": "Binary Search",
    "topicId": "pc-binary-search"
  },
  {
    "id": "pc-container-with-most-water",
    "slug": "container-with-most-water",
    "title": "Container With Most Water",
    "difficulty": "medium",
    "order": 61,
    "category": "greedy",
    "categoryLabel": "Greedy",
    "topicId": "pc-greedy"
  },
  {
    "id": "pc-permutations",
    "slug": "permutations",
    "title": "Permutations",
    "difficulty": "medium",
    "order": 63,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "pc-backtracking"
  },
  {
    "id": "pc-combinations",
    "slug": "combinations",
    "title": "Combinations",
    "difficulty": "medium",
    "order": 64,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "pc-backtracking"
  },
  {
    "id": "pc-letter-combinations-of-a-phone-number",
    "slug": "letter-combinations-of-a-phone-number",
    "title": "Letter Combinations of a Phone Number",
    "difficulty": "medium",
    "order": 65,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "pc-backtracking"
  },
  {
    "id": "pc-kth-largest-element-in-an-array",
    "slug": "kth-largest-element-in-an-array",
    "title": "Kth Largest Element in an Array",
    "difficulty": "medium",
    "order": 70,
    "category": "heap",
    "categoryLabel": "Heaps",
    "topicId": "pc-heap"
  },
  {
    "id": "pc-merge-intervals",
    "slug": "merge-intervals",
    "title": "Merge Intervals",
    "difficulty": "medium",
    "order": 72,
    "category": "intervals",
    "categoryLabel": "Intervals",
    "topicId": "pc-intervals"
  },
  {
    "id": "pc-set-matrix-zeroes",
    "slug": "set-matrix-zeroes",
    "title": "Set Matrix Zeroes",
    "difficulty": "medium",
    "order": 73,
    "category": "matrices",
    "categoryLabel": "Matrices",
    "topicId": "pc-matrices"
  },
  {
    "id": "pc-spiral-matrix",
    "slug": "spiral-matrix",
    "title": "Spiral Matrix",
    "difficulty": "medium",
    "order": 74,
    "category": "matrices",
    "categoryLabel": "Matrices",
    "topicId": "pc-matrices"
  },
  {
    "id": "pc-three-sum",
    "slug": "three-sum",
    "title": "3Sum",
    "difficulty": "medium",
    "order": 78,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-lowest-common-ancestor-of-a-binary-tree",
    "slug": "lowest-common-ancestor-of-a-binary-tree",
    "title": "Lowest Common Ancestor of a Binary Tree",
    "difficulty": "medium",
    "order": 82,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-maximum-product-subarray",
    "slug": "maximum-product-subarray",
    "title": "Maximum Product Subarray",
    "difficulty": "medium",
    "order": 84,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-reverse-integer",
    "slug": "reverse-integer",
    "title": "Reverse Integer",
    "difficulty": "medium",
    "order": 85,
    "category": "bit-manipulation",
    "categoryLabel": "Bit Manipulation",
    "topicId": "pc-bit-manipulation"
  },
  {
    "id": "pc-integer-to-roman",
    "slug": "integer-to-roman",
    "title": "Integer to Roman",
    "difficulty": "medium",
    "order": 86,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-palindrome-partitioning",
    "slug": "palindrome-partitioning",
    "title": "Palindrome Partitioning",
    "difficulty": "medium",
    "order": 87,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "pc-backtracking"
  },
  {
    "id": "pc-combination-sum",
    "slug": "combination-sum",
    "title": "Combination Sum",
    "difficulty": "medium",
    "order": 88,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "pc-backtracking"
  },
  {
    "id": "pc-implement-trie",
    "slug": "implement-trie",
    "title": "Implement Trie (Prefix Tree)",
    "difficulty": "medium",
    "order": 89,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-meeting-rooms-ii",
    "slug": "meeting-rooms-ii",
    "title": "Meeting Rooms II",
    "difficulty": "medium",
    "order": 92,
    "category": "intervals",
    "categoryLabel": "Intervals",
    "topicId": "pc-intervals"
  },
  {
    "id": "pc-decode-ways",
    "slug": "decode-ways",
    "title": "Decode Ways",
    "difficulty": "medium",
    "order": 95,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-different-ways-to-add-parentheses",
    "slug": "different-ways-to-add-parentheses",
    "title": "Different Ways to Add Parentheses",
    "difficulty": "medium",
    "order": 98,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pb-squares-generator",
    "slug": "squares-generator",
    "title": "Squares Generator",
    "difficulty": "hard",
    "order": 1,
    "category": "comprehensions",
    "categoryLabel": "Comprehensions",
    "topicId": "pb-comprehensions"
  },
  {
    "id": "pb-flatten-matrix",
    "slug": "flatten-matrix",
    "title": "Flatten a Matrix",
    "difficulty": "hard",
    "order": 2,
    "category": "comprehensions",
    "categoryLabel": "Comprehensions",
    "topicId": "pb-comprehensions"
  },
  {
    "id": "pb-repeat-decorator",
    "slug": "repeat-decorator",
    "title": "Repeat Decorator",
    "difficulty": "hard",
    "order": 3,
    "category": "decorators",
    "categoryLabel": "Decorators",
    "topicId": "pb-decorators"
  },
  {
    "id": "pb-custom-age-error",
    "slug": "custom-age-error",
    "title": "Raise a Custom Error",
    "difficulty": "hard",
    "order": 4,
    "category": "exceptions",
    "categoryLabel": "Exceptions",
    "topicId": "pb-exceptions"
  },
  {
    "id": "pb-person-special-methods",
    "slug": "person-special-methods",
    "title": "Person Special Methods",
    "difficulty": "hard",
    "order": 5,
    "category": "oop",
    "categoryLabel": "Classes & OOP",
    "topicId": "pb-oop"
  },
  {
    "id": "pb-extract-phones",
    "slug": "extract-phones",
    "title": "Extract Phone Numbers",
    "difficulty": "hard",
    "order": 6,
    "category": "regex",
    "categoryLabel": "Regular Expressions",
    "topicId": "pb-regex"
  },
  {
    "id": "pb-json-file-roundtrip",
    "slug": "json-file-roundtrip",
    "title": "JSON File Roundtrip",
    "difficulty": "hard",
    "order": 7,
    "category": "json",
    "categoryLabel": "JSON",
    "topicId": "pb-json"
  },
  {
    "id": "pb-make-multiplier",
    "slug": "make-multiplier",
    "title": "Multiplier Closure",
    "difficulty": "hard",
    "order": 8,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-make-counter",
    "slug": "make-counter",
    "title": "Counter Closure",
    "difficulty": "hard",
    "order": 9,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-fibonacci-generator",
    "slug": "fibonacci-generator",
    "title": "Fibonacci Generator",
    "difficulty": "hard",
    "order": 10,
    "category": "comprehensions",
    "categoryLabel": "Comprehensions",
    "topicId": "pb-comprehensions"
  },
  {
    "id": "pb-prime-sieve-gen",
    "slug": "prime-sieve-gen",
    "title": "Prime Generator",
    "difficulty": "hard",
    "order": 11,
    "category": "comprehensions",
    "categoryLabel": "Comprehensions",
    "topicId": "pb-comprehensions"
  },
  {
    "id": "pb-word-frequency-map",
    "slug": "word-frequency-map",
    "title": "Word Frequency Map",
    "difficulty": "hard",
    "order": 12,
    "category": "comprehensions",
    "categoryLabel": "Comprehensions",
    "topicId": "pb-comprehensions"
  },
  {
    "id": "pb-shape-inheritance",
    "slug": "shape-inheritance",
    "title": "Shape and Circle",
    "difficulty": "hard",
    "order": 13,
    "category": "oop",
    "categoryLabel": "Classes & OOP",
    "topicId": "pb-oop"
  },
  {
    "id": "pb-celsius-property",
    "slug": "celsius-property",
    "title": "Temperature Property",
    "difficulty": "hard",
    "order": 14,
    "category": "oop",
    "categoryLabel": "Classes & OOP",
    "topicId": "pb-oop"
  },
  {
    "id": "pb-employee-hierarchy",
    "slug": "employee-hierarchy",
    "title": "Employee Hierarchy",
    "difficulty": "hard",
    "order": 15,
    "category": "oop",
    "categoryLabel": "Classes & OOP",
    "topicId": "pb-oop"
  },
  {
    "id": "pb-list-context-manager",
    "slug": "list-context-manager",
    "title": "Append List Context Manager",
    "difficulty": "hard",
    "order": 16,
    "category": "oop",
    "categoryLabel": "Classes & OOP",
    "topicId": "pb-oop"
  },
  {
    "id": "pb-memoize-decorator",
    "slug": "memoize-decorator",
    "title": "Memoize Decorator",
    "difficulty": "hard",
    "order": 17,
    "category": "decorators",
    "categoryLabel": "Decorators",
    "topicId": "pb-decorators"
  },
  {
    "id": "pb-log-calls-decorator",
    "slug": "log-calls-decorator",
    "title": "Log Calls Decorator",
    "difficulty": "hard",
    "order": 18,
    "category": "decorators",
    "categoryLabel": "Decorators",
    "topicId": "pb-decorators"
  },
  {
    "id": "pb-positive-args-only",
    "slug": "positive-args-only",
    "title": "Positive Args Decorator",
    "difficulty": "hard",
    "order": 19,
    "category": "decorators",
    "categoryLabel": "Decorators",
    "topicId": "pb-decorators"
  },
  {
    "id": "pb-extract-ipv4",
    "slug": "extract-ipv4",
    "title": "Extract IPv4 Addresses",
    "difficulty": "hard",
    "order": 20,
    "category": "regex",
    "categoryLabel": "Regular Expressions",
    "topicId": "pb-regex"
  },
  {
    "id": "pb-parse-log-fields",
    "slug": "parse-log-fields",
    "title": "Parse Log Fields",
    "difficulty": "hard",
    "order": 21,
    "category": "regex",
    "categoryLabel": "Regular Expressions",
    "topicId": "pb-regex"
  },
  {
    "id": "pb-merge-json-strings",
    "slug": "merge-json-strings",
    "title": "Merge JSON Strings",
    "difficulty": "hard",
    "order": 22,
    "category": "json",
    "categoryLabel": "JSON",
    "topicId": "pb-json"
  },
  {
    "id": "pb-invalid-score-error",
    "slug": "invalid-score-error",
    "title": "Invalid Score Error",
    "difficulty": "hard",
    "order": 23,
    "category": "exceptions",
    "categoryLabel": "Exceptions",
    "topicId": "pb-exceptions"
  },
  {
    "id": "pb-safe-divide-chain",
    "slug": "safe-divide-chain",
    "title": "Safe Divide Chain",
    "difficulty": "hard",
    "order": 24,
    "category": "exceptions",
    "categoryLabel": "Exceptions",
    "topicId": "pb-exceptions"
  },
  {
    "id": "pb-read-last-lines",
    "slug": "read-last-lines",
    "title": "Read Last N Lines",
    "difficulty": "hard",
    "order": 25,
    "category": "files",
    "categoryLabel": "Files",
    "topicId": "pb-files"
  },
  {
    "id": "pb-write-json-lines",
    "slug": "write-json-lines",
    "title": "Write JSON Lines File",
    "difficulty": "hard",
    "order": 26,
    "category": "files",
    "categoryLabel": "Files",
    "topicId": "pb-files"
  },
  {
    "id": "pb-parse-semver",
    "slug": "parse-semver",
    "title": "Parse Version String",
    "difficulty": "hard",
    "order": 27,
    "category": "modules",
    "categoryLabel": "Modules",
    "topicId": "pb-modules"
  },
  {
    "id": "pb-stdin-sum-evens",
    "slug": "stdin-sum-evens",
    "title": "Sum Evens From Input",
    "difficulty": "hard",
    "order": 28,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-stdin-email-redact",
    "slug": "stdin-email-redact",
    "title": "Redact Emails From Input",
    "difficulty": "hard",
    "order": 29,
    "category": "regex",
    "categoryLabel": "Regular Expressions",
    "topicId": "pb-regex"
  },
  {
    "id": "pb-stdin-json-greet",
    "slug": "stdin-json-greet",
    "title": "Greet From JSON Input",
    "difficulty": "hard",
    "order": 30,
    "category": "json",
    "categoryLabel": "JSON",
    "topicId": "pb-json"
  },
  {
    "id": "pb-dotted-path-get",
    "slug": "dotted-path-get",
    "title": "Dotted Path Lookup",
    "difficulty": "hard",
    "order": 31,
    "category": "dictionaries",
    "categoryLabel": "Dictionaries",
    "topicId": "pb-dictionaries"
  },
  {
    "id": "pb-function-compose",
    "slug": "function-compose",
    "title": "Compose Functions",
    "difficulty": "hard",
    "order": 32,
    "category": "functions",
    "categoryLabel": "Functions",
    "topicId": "pb-functions"
  },
  {
    "id": "pb-retry-on-exception",
    "slug": "retry-on-exception",
    "title": "Retry On Exception",
    "difficulty": "hard",
    "order": 33,
    "category": "decorators",
    "categoryLabel": "Decorators",
    "topicId": "pb-decorators"
  },
  {
    "id": "pc-first-missing-positive",
    "slug": "first-missing-positive",
    "title": "First Missing Positive",
    "difficulty": "hard",
    "order": 12,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-minimum-window-substring",
    "slug": "minimum-window-substring",
    "title": "Minimum Window Substring",
    "difficulty": "hard",
    "order": 25,
    "category": "strings",
    "categoryLabel": "Strings",
    "topicId": "pc-strings"
  },
  {
    "id": "pc-largest-rectangle-in-histogram",
    "slug": "largest-rectangle-in-histogram",
    "title": "Largest Rectangle in Histogram",
    "difficulty": "hard",
    "order": 36,
    "category": "stack-queue",
    "categoryLabel": "Stacks & Queues",
    "topicId": "pc-stack-queue"
  },
  {
    "id": "pc-binary-tree-maximum-path-sum",
    "slug": "binary-tree-maximum-path-sum",
    "title": "Binary Tree Maximum Path Sum",
    "difficulty": "hard",
    "order": 44,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-edit-distance",
    "slug": "edit-distance",
    "title": "Edit Distance",
    "difficulty": "hard",
    "order": 55,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-n-queens",
    "slug": "n-queens",
    "title": "N-Queens",
    "difficulty": "hard",
    "order": 66,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "pc-backtracking"
  },
  {
    "id": "pc-merge-k-sorted-lists",
    "slug": "merge-k-sorted-lists",
    "title": "Merge k Sorted Lists",
    "difficulty": "hard",
    "order": 71,
    "category": "heap",
    "categoryLabel": "Heaps",
    "topicId": "pc-heap"
  },
  {
    "id": "pc-median-of-two-sorted-arrays",
    "slug": "median-of-two-sorted-arrays",
    "title": "Median of Two Sorted Arrays",
    "difficulty": "hard",
    "order": 75,
    "category": "binary-search",
    "categoryLabel": "Binary Search",
    "topicId": "pc-binary-search"
  },
  {
    "id": "pc-trapping-rain-water",
    "slug": "trapping-rain-water",
    "title": "Trapping Rain Water",
    "difficulty": "hard",
    "order": 76,
    "category": "arrays",
    "categoryLabel": "Arrays & Lists",
    "topicId": "pc-arrays"
  },
  {
    "id": "pc-regular-expression-matching",
    "slug": "regular-expression-matching",
    "title": "Regular Expression Matching",
    "difficulty": "hard",
    "order": 77,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-word-ladder",
    "slug": "word-ladder",
    "title": "Word Ladder",
    "difficulty": "hard",
    "order": 79,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "pc-graphs"
  },
  {
    "id": "pc-burst-balloons",
    "slug": "burst-balloons",
    "title": "Burst Balloons",
    "difficulty": "hard",
    "order": 80,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-word-break-ii",
    "slug": "word-break-ii",
    "title": "Word Break II",
    "difficulty": "hard",
    "order": 81,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-serialize-and-deserialize-binary-tree",
    "slug": "serialize-and-deserialize-binary-tree",
    "title": "Serialize and Deserialize Binary Tree",
    "difficulty": "hard",
    "order": 83,
    "category": "trees",
    "categoryLabel": "Trees",
    "topicId": "pc-trees"
  },
  {
    "id": "pc-word-search-ii",
    "slug": "word-search-ii",
    "title": "Word Search II",
    "difficulty": "hard",
    "order": 90,
    "category": "backtracking",
    "categoryLabel": "Recursion & Backtracking",
    "topicId": "pc-backtracking"
  },
  {
    "id": "pc-alien-dictionary",
    "slug": "alien-dictionary",
    "title": "Alien Dictionary",
    "difficulty": "hard",
    "order": 91,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "pc-graphs"
  },
  {
    "id": "pc-reconstruct-itinerary",
    "slug": "reconstruct-itinerary",
    "title": "Reconstruct Itinerary",
    "difficulty": "hard",
    "order": 96,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "pc-graphs"
  },
  {
    "id": "pc-accounts-merge",
    "slug": "accounts-merge",
    "title": "Accounts Merge",
    "difficulty": "hard",
    "order": 97,
    "category": "graphs",
    "categoryLabel": "Graphs",
    "topicId": "pc-graphs"
  },
  {
    "id": "pc-wildcard-matching",
    "slug": "wildcard-matching",
    "title": "Wildcard Matching",
    "difficulty": "hard",
    "order": 99,
    "category": "dynamic-programming",
    "categoryLabel": "Dynamic Programming",
    "topicId": "pc-dynamic-programming"
  },
  {
    "id": "pc-fraction-to-recurring-decimal",
    "slug": "fraction-to-recurring-decimal",
    "title": "Fraction to Recurring Decimal",
    "difficulty": "hard",
    "order": 101,
    "category": "hash-maps",
    "categoryLabel": "Hash Maps",
    "topicId": "pc-hash-maps"
  }
];
